CREATE EXTERNAL FILE FORMAT [csvQuotedPipeSkipHeader] WITH
(
FORMAT_TYPE =  DELIMITEDTEXT,
FORMAT_OPTIONS
(
FIELD_TERMINATOR = N'|',
STRING_DELIMITER = N'"',
FIRST_ROW = 1,
USE_TYPE_DEFAULT = FALSE,
ENCODING = N'UTF8'
)
)
GO
