CREATE EXTERNAL FILE FORMAT [csvQuotedText] WITH
(
FORMAT_TYPE =  DELIMITEDTEXT,
FORMAT_OPTIONS
(
FIELD_TERMINATOR = N',',
STRING_DELIMITER = N'"',
FIRST_ROW = 1,
USE_TYPE_DEFAULT = TRUE,
ENCODING = N'UTF8'
)
)
GO
