create   view [blobTransInc].[VendTable] as select 
DML_Action,Start_LSN,Seq_Val,Instance,[AccountNum]
,[BankAccount]
,[BankCentralBankPurposeCode]
,[BankCentralBankPurposeText]
,[BankCentralBankTransTypeCur_RU]
,[BankOrderOfPayment_RU]
,[BidOnly]
,[BirthCountyCode_IT]
,[BirthPlace]
,[Blocked]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CustVendorBlocked' and e.EnumCode=t.[Blocked]) ,BlockedEnumID=[Blocked]
,[BlockedReleaseDate]
,[BLOCKEDRELEASEDATETZID]
,[CashDisc]
,[CCMNum_BR]
,[ChangeRequestAllowOverride]=case when [ChangeRequestAllowOverride]=1 then 'Yes' else 'No' end ,ChangeRequestAllowOverrideFlag=cast([ChangeRequestAllowOverride] as bit)
,[ChangeRequestEnabled]
,[ChangeRequestOverride]=case when [ChangeRequestOverride]=1 then 'Yes' else 'No' end ,ChangeRequestOverrideFlag=cast([ChangeRequestOverride] as bit)
,[CISCompanyRegNum]
,[CISNationalInsuranceNum]
,[CISStatus]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VendCISStatus' and e.EnumCode=t.[CISStatus]) ,CISStatusEnumID=[CISStatus]
,[CISUniqueTaxPayerRef]
,[CISVerificationDate]=cast([CISVerificationDate] as date)
,[CISVerificationNum]
,[ClearingPeriod]
,[CNAE_BR]
,[CNPJCPFNum_BR]
,[CodeRevenueTypology_IT]
,[COMMERCIALREGISTER]
,[COMMERCIALREGISTERINSETNUMBER]
,[COMMERCIALREGISTERSECTION]
,[CompanyChainId]
,[CompanyIdSiret]
,[CompanyNAFCode]
,[CompanyType_MX]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CompanyType_MX' and e.EnumCode=t.[CompanyType_MX]) ,CompanyType_MXEnumID=[CompanyType_MX]
,[ConsDay_JP]
,[ContactPersonId]
,[CREATEDBY]
,[CREATEDDATETIME]=cast([CREATEDDATETIME] as date)
,[CreditMax]
,[CreditRating]
,[Curp_MX]
,[Currency]
,[CXMLOrderEnable]
,[DataAreaId]
,[DataLakeModified_DateTime]=cast([DataLakeModified_DateTime] as datetime2(0))
,[DBA]
,[DefaultDimension]
,[DefaultInventStatusId]
,[DestinationCodeId]
,[DiotCountryCode_MX]
,[DisabledOwned]
,[DlvMode]
,[DlvTerm]
,[EInvoiceRegister_IT]
,[EndDisc]
,[EthnicOriginId]
,[FactoringAccount]
,[FATCAFilingRequirement]
,[FemaleOwned]
,[FineCode_BR]
,[FiscalCode]
,[ForeignEntityIndicator]
,[ForeignerId_BR]
,[ForeignResident_RU]
,[ForeignTaxRegistration_MX]
,[FreeNotesGroup_IT]
,[FreightZone]
,[GUPDiscountVendorClaimGroupName]
,[Heir_IT]
,[HUBZone]
,[ICMSContributor_BR]
,[IENum_BR]
,[InclTax]=case when [InclTax]=1 then 'Yes' else 'No' end ,InclTaxFlag=cast([InclTax] as bit)
,[INSSCEI_BR]
,[IntBank_LV]
,[InterestCode_BR]
,[InventLocation]
,[InventProfileId_RU]
,[InventProfileType_RU]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='InventProfileType_RU' and e.EnumCode=t.[InventProfileType_RU]) ,InventProfileType_RUEnumID=[InventProfileType_RU]
,[InventSiteId]
,[InvoiceAccount]
,[IsCPRB_BR]
,[IsPaymFeeCovered_JP]
,[IsPublicSector_IT]
,[IsResident_LV]
,[IsSelfInvoiceVendor_IT]
,[IsTaxationOverPayroll_BR]
,[ItemBuyerGroupId]
,[ITMAgent]
,[ITMCostTypeGroupId]
,[ITMFromPort]
,[ITMImportCostingVendor]
,[ITMOverUnderToleranceGroupId]
,[ITMServicesProvider]
,[ITMVendAccount]
,[ITMVendType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='ITMVendType' and e.EnumCode=t.[ITMVendType]) ,ITMVendTypeEnumID=[ITMVendType]
,[LegalRepresentativeCurp_MX]
,[LegalRepresentativeName_MX]
,[LegalRepresentativeRfc_MX]
,[LineDisc]
,[LineOfBusinessId]
,[LocallyOwned]
,[LvPaymTransCodes]
,[MainContactWorker]
,[MandatoryVatDate_PL]
,[MarkupGroup]
,[MatchingPolicy]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='PurchMatchingPolicyWithNotSetOption' and e.EnumCode=t.[MatchingPolicy]) ,MatchingPolicyEnumID=[MatchingPolicy]
,[MinorityOwned]
,[MODIFIEDBY]
,[MODIFIEDDATETIME]=cast([MODIFIEDDATETIME] as date)
,[MultiLineDisc]
,[NameControl]
,[Nationality_MX]
,[NIT_BR]
,[NonTaxable_BR]=case when [NonTaxable_BR]=1 then 'Yes' else 'No' end ,NonTaxable_BRFlag=cast([NonTaxable_BR] as bit)
,[numberSequenceGroup]
,[OffsetAccountType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='LedgerJournalACType' and e.EnumCode=t.[OffsetAccountType]) ,OffsetAccountTypeEnumID=[OffsetAccountType]
,[OffsetLedgerDimension]
,[OneTimeVendor]
,[OperationType_MX]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VendorOperationType_MX' and e.EnumCode=t.[OperationType_MX]) ,OperationType_MXEnumID=[OperationType_MX]
,[OrganizationNumber]
,[OrgId]
,[OriginalVendorInReporting_IT]
,[OverrideSalesTax]
,[PARTITION]
,[Party]
,[PaymDayId]
,[PaymId]
,[PaymMode]
,[PaymSched]
,[PaymSpec]
,[PaymTermId]
,[PresenceType_BR]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='EFDocPresenceType_BR' and e.EnumCode=t.[PresenceType_BR]) ,PresenceType_BREnumID=[PresenceType_BR]
,[PriceGroup]
,[PurchAmountPurchaseOrder]
,[PurchCalendarId]
,[PurchPoolId]
,[RECID]
,[RECVERSION]
,[ResidenceForeignCountryRegionId]
,[RevenueTypology_IT]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='RevenueTypology_IT' and e.EnumCode=t.[RevenueTypology_IT]) ,RevenueTypology_ITEnumID=[RevenueTypology_IT]
,[Rfc_MX]
,[SAB_ConsDirectLienWaiverRequireRecipientSpecification]=case when [SAB_ConsDirectLienWaiverRequireRecipientSpecification]=1 then 'Yes' else 'No' end ,SAB_ConsDirectLienWaiverRequireRecipientSpecificationFlag=cast([SAB_ConsDirectLienWaiverRequireRecipientSpecification] as bit)
,[SAB_ConsDirectLienWaiverRequireSMSAuth]=case when [SAB_ConsDirectLienWaiverRequireSMSAuth]=1 then 'Yes' else 'No' end ,SAB_ConsDirectLienWaiverRequireSMSAuthFlag=cast([SAB_ConsDirectLienWaiverRequireSMSAuth] as bit)
,[SAB_ConsDirectLienWaiverUseDocuSign]=case when [SAB_ConsDirectLienWaiverUseDocuSign]=1 then 'Yes' else 'No' end ,SAB_ConsDirectLienWaiverUseDocuSignFlag=cast([SAB_ConsDirectLienWaiverUseDocuSign] as bit)
,[SAB_ConsDirectLienWaiverVendType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='SAB_ConsDirectLienWaiverVendType' and e.EnumCode=t.[SAB_ConsDirectLienWaiverVendType]) ,SAB_ConsDirectLienWaiverVendTypeEnumID=[SAB_ConsDirectLienWaiverVendType]
,[SAB_ConsLandDeveloper]=case when [SAB_ConsLandDeveloper]=1 then 'Yes' else 'No' end ,SAB_ConsLandDeveloperFlag=cast([SAB_ConsLandDeveloper] as bit)
,[SAB_CONSUSEVENDPORTAL]
,[SecondTIN]=case when [SecondTIN]=1 then 'Yes' else 'No' end ,SecondTINFlag=cast([SecondTIN] as bit)
,[SegmentId]
,[SeparateDivisionId_RU]
,[ServiceCodeOnDlvAddress_BR]
,[SmallBusiness]
,[StateInscription_MX]
,[StructDepartment_RU]
,[SubsegmentId]
,[SuppItemGroupId]
,[TAMRebateGroupID]
,[Tax1099Fields]
,[Tax1099NameChoice]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='Tax1099NameChoice' and e.EnumCode=t.[Tax1099NameChoice]) ,Tax1099NameChoiceEnumID=[Tax1099NameChoice]
,[Tax1099RegNum]
,[Tax1099Reports]
,[TaxGroup]
,[TaxIDType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxIDType' and e.EnumCode=t.[TaxIDType]) ,TaxIDTypeEnumID=[TaxIDType]
,[TaxPeriodPaymentCode_PL]
,[TaxWithholdCalculate]
,[TaxWithholdGroup]
,[TaxWithholdVendorType_TH]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxWithholdVendorType_TH' and e.EnumCode=t.[TaxWithholdVendorType_TH]) ,TaxWithholdVendorType_THEnumID=[TaxWithholdVendorType_TH]
,[UnitedVATInvoice_LT]
,[UseCashDisc]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='UseCashDisc' and e.EnumCode=t.[UseCashDisc]) ,UseCashDiscEnumID=[UseCashDisc]
,[VATNum]
,[VATNumRecId]
,[VATNumTableType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxExemptNumberSourceType' and e.EnumCode=t.[VATNumTableType]) ,VATNumTableTypeEnumID=[VATNumTableType]
,[VATOperationCode_RU]
,[VATPartnerKind_RU]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VATPartnerKind_RU' and e.EnumCode=t.[VATPartnerKind_RU]) ,VATPartnerKind_RUEnumID=[VATPartnerKind_RU]
,[VATTaxAgent_RU]=case when [VATTaxAgent_RU]=1 then 'Yes' else 'No' end ,VATTaxAgent_RUFlag=cast([VATTaxAgent_RU] as bit)
,[VendConsumption_BR]
,[VendExceptionGroup]
,[VendGroup]
,[VendIncomeCode_BR]
,[VendInvoiceDeclaration_IS]
,[VendItemGroupId]
,[VENDORPORTALADMINISTRATORRECID]
,[VendorType_MX]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VendorType_MX' and e.EnumCode=t.[VendorType_MX]) ,VendorType_MXEnumID=[VendorType_MX]
,[VendPaymFeeGroup_JP]
,[VendPriceToleranceGroupId]
,[VendVendorCollaborationType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VendVendorCollaborationType' and e.EnumCode=t.[VendVendorCollaborationType]) ,VendVendorCollaborationTypeEnumID=[VendVendorCollaborationType]
,[VeteranOwned]
,[W9]
,[W9Included]
,[WithholdingTaxpayerType_MX]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CFDIWithholdingTaxpayerType_MX' and e.EnumCode=t.[WithholdingTaxpayerType_MX]) ,WithholdingTaxpayerType_MXEnumID=[WithholdingTaxpayerType_MX]
,[WithholdingTypeCode_MX]
,[WorkflowState]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VendTableChangeProposalWorkflowState' and e.EnumCode=t.[WorkflowState]) ,WorkflowStateEnumID=[WorkflowState]
,[YourAccountNum]
 from stage.VendTable t
GO
