create   view [blobTransInc].[LedgerJournalTrans] as select 
DML_Action,Start_LSN,Seq_Val,Instance,[AccountAgreementId_RU]
,[AccountType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='LedgerJournalACType' and e.EnumCode=t.[AccountType]) ,AccountTypeEnumID=[AccountType]
,[AcknowledgementDate]=cast([AcknowledgementDate] as date)
,[Addressing_PL]
,[AgreementCompany_RU]
,[AmountCurCredit]=cast([AmountCurCredit] as numeric(18,2))
,[AmountCurDebit]=cast([AmountCurDebit] as numeric(18,2))
,[AnnouncementNum_RU]
,[Approved]
,[Approver]
,[AssetLeasePostingTypes]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='AssetLeasePostingTypes' and e.EnumCode=t.[AssetLeasePostingTypes]) ,AssetLeasePostingTypesEnumID=[AssetLeasePostingTypes]
,[AssetLeaseStatus]
,[Attachments_CN]
,[BankAccountId]
,[BankAgreementExt_RU]
,[BankBillOfExchangeNum]
,[BankCentralBankPurposeCode]
,[BankCentralBankPurposeText]
,[BankCentralBankTransTypeCur_RU]
,[BankChequeDepositTransRefRecID]
,[BankChequeNum]
,[BankClientDocumentTypeId_RU]
,[BankCommAccountId_RU]
,[BankCurrency]
,[BankCurrencyAmount]=cast([BankCurrencyAmount] as numeric(18,2))
,[BankCurrencyDealCourse_RU]
,[BankCurrencyTransferLog_RU]
,[BankDepositNum]
,[BankDepositVoucher]
,[BankNegInstRecipientName]
,[BankPaymentRegistrationNum_LV]
,[BankPrintAccountNum_RU]
,[BankPromissoryNoteNum]
,[BankReconcileAccountAtPost]=case when [BankReconcileAccountAtPost]=1 then 'Yes' else 'No' end ,BankReconcileAccountAtPostFlag=cast([BankReconcileAccountAtPost] as bit)
,[BankRemittanceFileId]
,[BankRemittanceType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='BankRemittanceType' and e.EnumCode=t.[BankRemittanceType]) ,BankRemittanceTypeEnumID=[BankRemittanceType]
,[BankRespWorkerId_RU]
,[BankSpecAccountId_RU]
,[BankTransType]
,[BankVendAccountId_RU]
,[BudgetSourceLedgerEntryUnposted]
,[Cancel]
,[CashDiscAmount]=cast([CashDiscAmount] as numeric(18,2))
,[CashDiscBaseDate]=cast([CashDiscBaseDate] as date)
,[CashDiscBaseDays]
,[CashDiscCode]
,[CashDiscPercent]
,[CashReceiptNum_LV]
,[CFDIUUID_MX]
,[CommProfileType_RU]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CommProfileType_RU' and e.EnumCode=t.[CommProfileType_RU]) ,CommProfileType_RUEnumID=[CommProfileType_RU]
,[Company]
,[Correct_RU]
,[CorrectedInvoiceDate_RU]=cast([CorrectedInvoiceDate_RU] as date)
,[CorrectedInvoiceId_RU]
,[CorrectionType_RU]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='FactureCorrectionType_RU' and e.EnumCode=t.[CorrectionType_RU]) ,CorrectionType_RUEnumID=[CorrectionType_RU]
,[CreditCardAuthTransRefId]
,[CurrencyCode]
,[CustBankAccount]
,[CustEinvoicePaymDeliveryNum]
,[CustEinvoicePaymSectionNum]
,[CustEinvoicePaymTransNum]
,[CustFactureAutoCreate_RU]
,[CustTransId]
,[CustVendAccount_PL]
,[CustVendBankAccountId]
,[CustVendName_PL]
,[CustVendNegInstProtestReason]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CustVendNegInstProtestReason' and e.EnumCode=t.[CustVendNegInstProtestReason]) ,CustVendNegInstProtestReasonEnumID=[CustVendNegInstProtestReason]
,[DataAreaId]
,[DataLakeModified_DateTime]=cast([DataLakeModified_DateTime] as datetime2(0))
,[DateCashDisc]=cast([DateCashDisc] as date)
,[DebitCurrencyCode_LT]
,[DefaultDimension]
,[DelayTaxCalculation]=case when [DelayTaxCalculation]=1 then 'Yes' else 'No' end ,DelayTaxCalculationFlag=cast([DelayTaxCalculation] as bit)
,[DirectDebitMandate]
,[DocumentDate]=cast([DocumentDate] as date)
,[DocumentNum]
,[Due]=cast([Due] as date)
,[ElectronicPaymentNumber]
,[EnterpriseNumber]
,[ErrorCodePayment]
,[EUSalesList]
,[ExchRate]
,[ExchRateSecond]
,[FBSpedEcfDerexClasificationCode_BR]
,[FileCreated]=cast([FileCreated] as date)
,[ForeignCompany]
,[ForeignVoucher]
,[FreqCode]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='PeriodUnit' and e.EnumCode=t.[FreqCode]) ,FreqCodeEnumID=[FreqCode]
,[FreqValue]
,[FurtherPostingRecId]
,[FurtherPostingType]
,[GSTHSTTaxType_CA]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='GSTHSTTaxType_CA' and e.EnumCode=t.[GSTHSTTaxType_CA]) ,GSTHSTTaxType_CAEnumID=[GSTHSTTaxType_CA]
,[ImportDate]=cast([ImportDate] as date)
,[InformByPhone_LT]
,[InformByTelex_LT]
,[IntBank_LV]
,[IntentLetterId_IT]
,[IntraComVATDueDate_W]
,[Invisible]=case when [Invisible]=1 then 'Yes' else 'No' end ,InvisibleFlag=cast([Invisible] as bit)
,[Invoice]
,[InvoiceReleaseDate]
,[INVOICERELEASEDATETZID]
,[InvoiceSeries_MX]
,[ITMCostArea]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='ITMCostArea' and e.EnumCode=t.[ITMCostArea]) ,ITMCostAreaEnumID=[ITMCostArea]
,[ITMCostRefRecId]
,[ITMCostTypeId]
,[JournalNum]
,[LastTransferred]=cast([LastTransferred] as date)
,[LedgerDimension]
,[LedgerDimensionName]
,[LedgerJournalDlvDate_ES]=cast([LedgerJournalDlvDate_ES] as date)
,[LedgerVoucherType_CN]
,[LineNum]=cast([LineNum] as numeric(18,2))
,[Listcode]
,[LoadingDate]=cast([LoadingDate] as date)
,[MarkedInvoice]
,[MarkedInvoiceCompany]
,[MarkedInvoiceRecId]
,[MarkupCode_RU]
,[MCRCCGeneralLedgerId]
,[MCRPaymOrderID]
,[MCRPrintTxtOnCheck]
,[MCRRefPaymID]
,[MODIFIEDDATETIME]=cast([MODIFIEDDATETIME] as date)
,[NegInstId]
,[NoEdit]=case when [NoEdit]=1 then 'Yes' else 'No' end ,NoEditFlag=cast([NoEdit] as bit)
,[OffSessionId_RU]
,[OffsetAccountAgreementId_RU]
,[OffsetAccountType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='LedgerJournalACType' and e.EnumCode=t.[OffsetAccountType]) ,OffsetAccountTypeEnumID=[OffsetAccountType]
,[OffsetAgreementCompany_RU]
,[OffsetCompany]
,[OffsetDefaultDimension]
,[OffsetLedgerDimension]
,[OffsetPostingProfile_RU]
,[OffsetTxt]
,[OperationType_MX]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VendorOperationType_MX' and e.EnumCode=t.[OperationType_MX]) ,OperationType_MXEnumID=[OperationType_MX]
,[PARTITION]
,[Payment]
,[PaymentAccount]
,[PaymentNotes]
,[PaymentSequenceNum]
,[PaymentStatus]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CustVendPaymStatus' and e.EnumCode=t.[PaymentStatus]) ,PaymentStatusEnumID=[PaymentStatus]
,[PaymId]
,[PaymInstruction1]
,[PaymInstruction2]
,[PaymInstruction3]
,[PaymInstruction4]
,[PaymMode]
,[PaymPurpose_LT]
,[PaymReference]
,[PaymSched]
,[PaymSpec]
,[PlafondDate_IT]=cast([PlafondDate_IT] as date)
,[PoolRecId]
,[PostingProfile]
,[Prepayment]=case when [Prepayment]=1 then 'Yes' else 'No' end ,PrepaymentFlag=cast([Prepayment] as bit)
,[Price]=cast([Price] as numeric(18,2))
,[ProvisionalAssessment_IN]
,[PurchIdRange]
,[PurchLedgerPosting]
,[Qty]
,[RCashDocRepresPersonId]
,[RCashDocRepresType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='RCashDocRepresType' and e.EnumCode=t.[RCashDocRepresType]) ,RCashDocRepresTypeEnumID=[RCashDocRepresType]
,[RCashPayTransType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='RCashPayLedgerTransType' and e.EnumCode=t.[RCashPayTransType]) ,RCashPayTransTypeEnumID=[RCashPayTransType]
,[ReasonRefRecID]
,[ReceiptDate_W]=cast([ReceiptDate_W] as date)
,[RECID]
,[RECVERSION]
,[RefCopyReverse_CN]
,[ReleaseDate]=cast([ReleaseDate] as date)
,[ReleaseDateComment]
,[RELEASEDATETZID]
,[RemainAmount]=cast([RemainAmount] as numeric(18,2))
,[RemittanceAddress]
,[RemittanceLocation]
,[RemitteeCurrency]
,[ReportingCurrencyExchRate]
,[ReportingCurrencyExchRateSecondary]
,[RepresPersonCard_W]
,[RepresPersonName_W]
,[ReverseDate]=cast([ReverseDate] as date)
,[ReverseEntry]=case when [ReverseEntry]=1 then 'Yes' else 'No' end ,ReverseEntryFlag=cast([ReverseEntry] as bit)
,[RevRecDeferredLine]
,[RevRecDeferredRecognizedQty]=cast([RevRecDeferredRecognizedQty] as numeric(18,6))
,[RevRecDeferredType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='RevRecDeferredType' and e.EnumCode=t.[RevRecDeferredType]) ,RevRecDeferredTypeEnumID=[RevRecDeferredType]
,[RevRecId]
,[RevRecLedgerPostingType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='LedgerPostingType' and e.EnumCode=t.[RevRecLedgerPostingType]) ,RevRecLedgerPostingTypeEnumID=[RevRecLedgerPostingType]
,[RevRecNewValuesFromReallocation]
,[RevRecSalesId]
,[SalesOrderId]
,[SettleVoucher]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='SettlementType' and e.EnumCode=t.[SettleVoucher]) ,SettleVoucherEnumID=[SettleVoucher]
,[SkipBlockedForManualEntryCheck]=case when [SkipBlockedForManualEntryCheck]=1 then 'Yes' else 'No' end ,SkipBlockedForManualEntryCheckFlag=cast([SkipBlockedForManualEntryCheck] as bit)
,[SubBillEscalationTableRecId]
,[SubBillRenewalLineRecId]
,[SubBillSchedLineRecId]
,[Tax1099Amount]=cast([Tax1099Amount] as numeric(18,2))
,[Tax1099Fields]
,[Tax1099RecId]
,[Tax1099State]
,[Tax1099StateAmount]=cast([Tax1099StateAmount] as numeric(18,2))
,[TaxBase_W]
,[TaxCode]
,[TaxDirectionControl]=case when [TaxDirectionControl]=1 then 'Yes' else 'No' end ,TaxDirectionControlFlag=cast([TaxDirectionControl] as bit)
,[TaxGroup]
,[TaxItemGroup]
,[TaxPeriodPaymentCode_PL]
,[TaxWithholdAlternateVendorAcct_TH]
,[TaxWithholdCalculate_TH]
,[TaxWithholdGroup]
,[TaxWithholdItemGroupHeading_TH]
,[TransactionType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='LedgerTransType' and e.EnumCode=t.[TransactionType]) ,TransactionTypeEnumID=[TransactionType]
,[TransDate]=cast([TransDate] as date)
,[Transfer]=case when [Transfer]=1 then 'Yes' else 'No' end ,TransferFlag=cast([Transfer] as bit)
,[TransferCurrency_RU]
,[Transferred]=case when [Transferred]=1 then 'Yes' else 'No' end ,TransferredFlag=cast([Transferred] as bit)
,[TransferredBy]
,[TransferredOn]=cast([TransferredOn] as date)
,[TransferredTo]
,[Triangulation]
,[Txt]
,[UseOriginalDocumentAsFacture_RU]
,[VatDueDate_W]=cast([VatDueDate_W] as date)
,[VATNumJournal]
,[VATOnPayment_RU]
,[VATOperationCode_RU]
,[VATPaymRefRecId_RU]
,[VATTaxAgentVendAccount_RU]
,[VendBankAccount]
,[VendInvoiceDeclaration_IS]
,[VendorVATDate]=cast([VendorVATDate] as date)
,[VendPaymFeeGroup_JP]
,[VendTransId]
,[Voucher]
,[Voucher_CN]
 from stage.LedgerJournalTrans t
GO
