create   view [blobTransInc].[CustTable] as select 
DML_Action,Start_LSN,Seq_Val,Instance,[AccountNum]
,[AccountStatement]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CustAccountStatement' and e.EnumCode=t.[AccountStatement]) ,AccountStatementEnumID=[AccountStatement]
,[Affiliated_RU]
,[AgencyLocationCode]
,[AuthorityOffice_IT]
,[BankAccount]
,[BankCentralBankPurposeCode]
,[BankCentralBankPurposeText]
,[BankCustPaymIdTable]
,[BirthCountyCode_IT]
,[BirthPlace_IT]
,[Blocked]
,[BlockFloorLimitUseInChannel]
,[CashDisc]
,[CashDiscBaseDays]
,[CCMNum_BR]
,[CFDIEnabled_MX]
,[CFDISkipIEPSTaxes_MX]
,[CFDITemporaryExport_MX]
,[ClearingPeriod]
,[CNAE_BR]
,[CNPJCPFNum_BR]
,[CollectionLetterCode]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CustCollectionLetterCode' and e.EnumCode=t.[CollectionLetterCode]) ,CollectionLetterCodeEnumID=[CollectionLetterCode]
,[COMMERCIALREGISTER]
,[COMMERCIALREGISTERINSETNUMBER]
,[COMMERCIALREGISTERSECTION]
,[CommissionGroup]
,[CompanyChainId]
,[CompanyIdSiret]
,[CompanyNAFCode]
,[CompanyType_MX]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CompanyType_MX' and e.EnumCode=t.[CompanyType_MX]) ,CompanyType_MXEnumID=[CompanyType_MX]
,[ConsDay_JP]
,[ContactPersonId]
,[CREATEDDATETIME]=cast([CREATEDDATETIME] as date)
,[CreditCardAddressVerification]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CreditCardAddressVerification' and e.EnumCode=t.[CreditCardAddressVerification]) ,CreditCardAddressVerificationEnumID=[CreditCardAddressVerification]
,[CreditCardAddressVerificationLevel]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CreditCardAddressVerificationLevel' and e.EnumCode=t.[CreditCardAddressVerificationLevel]) ,CreditCardAddressVerificationLevelEnumID=[CreditCardAddressVerificationLevel]
,[CreditCardAddressVerificationVoid]
,[CreditCardCVC]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CreditCardCVC' and e.EnumCode=t.[CreditCardCVC]) ,CreditCardCVCEnumID=[CreditCardCVC]
,[CreditMax]
,[CreditRating]
,[CredManAccountStatusId]
,[CredManBusinessStarted]=cast([CredManBusinessStarted] as date)
,[CredManCollectionGroupId]
,[CredManCreditLimitDate]=cast([CredManCreditLimitDate] as date)
,[CredManCreditLimitExpiryDate]=cast([CredManCreditLimitExpiryDate] as date)
,[CredManCustCreditMaxAlt]
,[CredManCustomerSince]=cast([CredManCustomerSince] as date)
,[CredManCustUnlimitedCredit]
,[CredManEligibleCreditLimitCurrency]
,[CredManEligibleCreditLimitDate]=cast([CredManEligibleCreditLimitDate] as date)
,[CredManEligibleCreditMax]
,[CredManExclude]
,[CredManGroupId]
,[CredManLastReviewDate]=cast([CredManLastReviewDate] as date)
,[CredManNextSchedReviewDate]=cast([CredManNextSchedReviewDate] as date)
,[CredManStatusReasonId]
,[CredManTitleHeld]
,[CredManWithAgency]
,[Curp_MX]
,[Currency]
,[CustClassificationId]
,[CustExcludeCollectionFee]
,[CustExcludeInterestCharges]
,[CustFinalUser_BR]
,[CustGroup]
,[CustItemGroupId]
,[CustTradingPartnerCode]
,[CustWhtContributionType_BR]
,[CustWriteOffRefRecId]
,[DataAreaId]
,[DataLakeModified_DateTime]=cast([DataLakeModified_DateTime] as datetime2(0))
,[DefaultDimension]
,[DefaultDirectDebitMandate]
,[DefaultInventStatusId]
,[DestinationCodeId]
,[DlvMode]
,[DlvReason]
,[DlvTerm]
,[EInvoice]
,[EInvoiceAttachment]
,[EinvoiceEANNum]
,[EInvoiceRegister_IT]
,[EndDisc]
,[EntryCertificateRequired_W]
,[ExportSales_PL]
,[ExpressBillOfLading]
,[FactoringAccount]
,[FederalComments]
,[FedNonFedIndicator]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='FederalNonFederalIndicatorCode' and e.EnumCode=t.[FedNonFedIndicator]) ,FedNonFedIndicatorEnumID=[FedNonFedIndicator]
,[FineCode_BR]
,[FiscalCode]
,[FiscalDocType_PL]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='PlFiscalDocType' and e.EnumCode=t.[FiscalDocType_PL]) ,FiscalDocType_PLEnumID=[FiscalDocType_PL]
,[ForecastDMPInclude]
,[ForeignerId_BR]
,[ForeignResident_RU]
,[ForeignTaxRegistration_MX]
,[ForeignTrade_MX]
,[FreeNotesGroup_IT]
,[FreightZone]
,[GenerateIncomingFiscalDocument_BR]
,[GiroType]
,[GiroTypeAccountStatement]
,[GiroTypeCollectionletter]
,[GiroTypeFreeTextInvoice]
,[GiroTypeInterestNote]
,[GiroTypeProjInvoice]
,[ICMSContributor_BR]
,[IdentificationNumber]
,[IENum_BR]
,[InclTax]
,[INSSCEI_BR]
,[IntBank_LV]
,[InterCompanyAllowIndirectCreation]
,[InterCompanyAutoCreateOrders]
,[InterCompanyDirectDelivery]
,[InterestCode_BR]
,[InventLocation]
,[InventProfileId_RU]
,[InventProfileType_RU]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='InventProfileType_RU' and e.EnumCode=t.[InventProfileType_RU]) ,InventProfileType_RUEnumID=[InventProfileType_RU]
,[InventSiteId]
,[InvoiceAccount]
,[InvoiceAddress]
,[InvoicePostingType_RU]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='SalesInvoicePostingType_RU' and e.EnumCode=t.[InvoicePostingType_RU]) ,InvoicePostingType_RUEnumID=[InvoicePostingType_RU]
,[InvoiceType_W]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='InvoiceType_W' and e.EnumCode=t.[InvoiceType_W]) ,InvoiceType_WEnumID=[InvoiceType_W]
,[IRS1099CIndicator]
,[IsExternallyMaintained]
,[IsPublicSector_IT]
,[IsResident_LV]
,[IssueOwnEntryCertificate_W]
,[IssuerCountry_HU]
,[LineDisc]
,[LineOfBusinessId]
,[LvPaymTransCodes]
,[MainContactWorker]
,[MandatoryCreditLimit]
,[MandatoryVatDate_PL]
,[MarkupGroup]
,[MCRMergedParent]
,[MCRMergedRoot]
,[MODIFIEDBY]
,[MODIFIEDDATETIME]=cast([MODIFIEDDATETIME] as date)
,[MultiLineDisc]
,[NIT_BR]
,[numberSequenceGroup]
,[OneTimeCustomer]
,[OrderEntryDeadlineGroupId]
,[OrgId]
,[OurAccountNum]
,[OverrideSalesTax]
,[PackageDepositExcempt_PL]
,[PackMaterialFeeLicenseNum]
,[PARTITION]
,[Party]
,[PartyCountry]
,[PartyState]
,[PassportNo_HU]
,[PaymDayId]
,[PaymentReference_EE]
,[PaymIdType]
,[PaymMode]
,[PaymSched]
,[PaymSpec]
,[PaymTermId]
,[PdsCustRebateGroupId]
,[PdsFreightAccrued]
,[PdsRebateTMAGroup]
,[PresenceType_BR]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='EFDocPresenceType_BR' and e.EnumCode=t.[PresenceType_BR]) ,PresenceType_BREnumID=[PresenceType_BR]
,[PriceGroup]
,[PrintDynamicQRCode_IN]
,[RECID]
,[RECVERSION]
,[ResidenceForeignCountryRegionId_IT]
,[RevRecDisableIntercompany]
,[Rfc_MX]
,[RFIDCASETAGGING]
,[RFIDITEMTAGGING]
,[RFIDPALLETTAGGING]
,[SalesCalendarId]
,[SalesDistrictId]
,[SalesGroup]
,[SalesPoolId]
,[SATPaymMethod_MX]
,[SATPurpose_MX]
,[SATRegistrationName_MX]
,[SegmentId]
,[ServiceCodeOnDlvAddress_BR]
,[ShipCarrierAccount]
,[ShipCarrierAccountCode]
,[ShipCarrierBlindShipment]
,[ShipCarrierFuelSurcharge]
,[ShipCarrierId]
,[SimpleNational_BR]
,[SimplifyTaxIntgrExportDocValidation_CN]=case when [SimplifyTaxIntgrExportDocValidation_CN]=1 then 'Yes' else 'No' end ,SimplifyTaxIntgrExportDocValidation_CNFlag=cast([SimplifyTaxIntgrExportDocValidation_CN] as bit)
,[SimplifyTaxIntgrExportTaxRegValidation_CN]=case when [SimplifyTaxIntgrExportTaxRegValidation_CN]=1 then 'Yes' else 'No' end ,SimplifyTaxIntgrExportTaxRegValidation_CNFlag=cast([SimplifyTaxIntgrExportTaxRegValidation_CN] as bit)
,[StateInscription_MX]
,[StatisticsGroup]
,[SubsegmentId]
,[Suframa_BR]
,[SuframaNumber_BR]
,[SuframaPISCOFINS_BR]=case when [SuframaPISCOFINS_BR]=1 then 'Yes' else 'No' end ,SuframaPISCOFINS_BRFlag=cast([SuframaPISCOFINS_BR] as bit)
,[SuppItemGroupId]
,[TaxGroup]
,[TaxGSTReliefGroupHeading_MY]
,[TaxLicenseNum]
,[TaxPeriodPaymentCode_PL]
,[TaxRegimeCode_MX]
,[TaxWithholdCalculate_IN]
,[TaxWithholdCalculate_TH]
,[TaxWithholdGroup_TH]
,[UnitedVATInvoice_LT]
,[UseCashDisc]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='UseCashDisc' and e.EnumCode=t.[UseCashDisc]) ,UseCashDiscEnumID=[UseCashDisc]
,[UseOriginalDocumentAsFacture_RU]
,[usePurchRequest]
,[UsualExporter_IT]=case when [UsualExporter_IT]=1 then 'Yes' else 'No' end ,UsualExporter_ITFlag=cast([UsualExporter_IT] as bit)
,[VATNum]
,[VATNumRecId]
,[VATNumTableType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxExemptNumberSourceType' and e.EnumCode=t.[VATNumTableType]) ,VATNumTableTypeEnumID=[VATNumTableType]
,[VendAccount]
,[WebSalesOrderDisplay]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='ECPsalesOrdersViewType' and e.EnumCode=t.[WebSalesOrderDisplay]) ,WebSalesOrderDisplayEnumID=[WebSalesOrderDisplay]
,[WorkflowState]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='CustTableChangeProposalWorkflowState' and e.EnumCode=t.[WorkflowState]) ,WorkflowStateEnumID=[WorkflowState]
 from stage.CustTable t
GO
