create   view [blobTransFull].[VendBankAccount] as select 
LSN,[AccountID]
,[AccountNum]
,[ActiveDate]
,[ACTIVEDATETZID]
,[BankAccountNameKana_JP]
,[BankAccountType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='BankAccountType' and e.EnumCode=t.[BankAccountType]) ,BankAccountTypeEnumID=[BankAccountType]
,[BankCIN]
,[BankCodeType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='BankCodeType' and e.EnumCode=t.[BankCodeType]) ,BankCodeTypeEnumID=[BankCodeType]
,[BankConstantSymbol]
,[BankContractAccount]
,[BankGroupID]
,[BankIBAN]
,[BankInformationOrigin]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='BankInformationOrigin' and e.EnumCode=t.[BankInformationOrigin]) ,BankInformationOriginEnumID=[BankInformationOrigin]
,[CellularPhone]
,[Comments]
,[ContactPerson]
,[CorrAccount_W]
,[CorrespBank_EE]
,[CREATEDBY]
,[CREATEDDATETIME]=cast([CREATEDDATETIME] as date)
,[CurrencyCode]
,[DataAreaId]
,[DataLakeModified_DateTime]=cast([DataLakeModified_DateTime] as datetime2(0))
,[DirDunsNumber]
,[Email]
,[ExchRate]
,[ExchRateRef]
,[ExpiryDate]=cast(case when [ExpiryDate] < cast('1901-01-01' as date) or [ExpiryDate] is null then '9000-01-01' else [ExpiryDate] end as date)
,[EXPIRYDATETZID]
,[FICreditorID_DK]
,[ForeignAccount_RU]
,[ForeignBank_RU]
,[ForeignSWIFT_RU]
,[IntermAccount_EE]
,[IntermBank_EE]
,[IntermBankAccountId]
,[Location]
,[LogisticsLocation]
,[LvDefaultBank]
,[MODIFIEDBY]
,[MODIFIEDDATETIME]=cast([MODIFIEDDATETIME] as date)
,[MsgToBank]
,[Name]
,[Pager]
,[PARTITION]
,[Phone]
,[PhoneLocal]
,[QRIBAN_CH]
,[RECID]
,[RECVERSION]
,[RegistrationNum]
,[Reviewed]=case when [Reviewed]=1 then 'Yes' else 'No' end ,ReviewedFlag=cast([Reviewed] as bit)
,[SMS]
,[SpecificSymbol]
,[SpecParameters_CH]
,[SWIFTNo]
,[TeleFax]
,[Telex]
,[TransType_JP]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='VendBankTransType_JP' and e.EnumCode=t.[TransType_JP]) ,TransType_JPEnumID=[TransType_JP]
,[URL]
,[VendAccount]
,[VendDuns4Number]
,[VendPaymentTextCode]
 from blobFull.VendBankAccount t
GO
