create   view [blobTransFull].[SAB_ConsFinancialInstance] as select 
LSN,[ACCRUED]
,[Active]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='SAB_ConsFinancialActive' and e.EnumCode=t.[Active]) ,ActiveEnumID=[Active]
,[AllocationExclude]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='SAB_ConsAllocationExclude' and e.EnumCode=t.[AllocationExclude]) ,AllocationExcludeEnumID=[AllocationExclude]
,[BillingTemplate]
,[BudgetDatesLocked]
,[CLOSED]
,[DataArea]
,[DataLakeModified_DateTime]=cast([DataLakeModified_DateTime] as datetime2(0))
,[DEFAULTDIMENSION]
,[DEFAULTDIMENSIONSELLING]
,[Description]
,[FINALIZATIONSTATUS]
,[FINALIZED]
,[FinancialInstanceId]
,[InstanceRelationType]
,[LOT]
,[LOTSTRUCTUREELEMENT]
,[Name]
,[PARTITION]
,[PostingGroup]
,[RECID]
,[RECVERSION]
,[RELATIONTYPE]
,[ReleaseGroup]
,[TAXENTITY]
,[TaxGroup]
 from blobFull.SAB_ConsFinancialInstance t
GO
