create   view [blobTransFull].[LogisticsPostalAddress] as select 
LSN,[Address]
,[Apartment_RU]
,[Building_RU]
,[BuildingCompliment]
,[ChannelReferenceId]
,[City]
,[CityKana_JP]
,[CityRecId]
,[CountryRegionId]
,[County]
,[DataLakeModified_DateTime]=cast([DataLakeModified_DateTime] as datetime2(0))
,[District]
,[DistrictName]
,[FlatId_RU]
,[HouseId_RU]
,[IsPrivate]
,[IsSimplifiedAddress_RU]
,[Latitude]
,[LocalityRecId]
,[Location]
,[Longitude]
,[MODIFIEDBY]
,[MODIFIEDDATETIME]=cast([MODIFIEDDATETIME] as date)
,[PARTITION]
,[PostBox]
,[PrivateForParty]
,[RECID]
,[RECVERSION]
,[SettlementRecId]
,[State]
,[SteadId_RU]
,[Street]
,[StreetId_RU]
,[StreetKana_JP]
,[StreetNumber]
,[TimeZone]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='Timezone' and e.EnumCode=t.[TimeZone]) ,TimeZoneEnumID=[TimeZone]
,[ValidFrom]=cast([ValidFrom] as date)
,[VALIDFROMTZID]
,[ValidTo]=cast([ValidTo] as date)
,[VALIDTOTZID]
,[ZipCode]
,[ZipCodeRecId]
 from blobFull.LogisticsPostalAddress t
GO
