create   view [blobTransInc].[TaxTrans] as select 
DML_Action,Start_LSN,Seq_Val,Instance,[CREATEDBY]
,[CREATEDDATETIME]=cast([CREATEDDATETIME] as date)
,[CurrencyCode]
,[DataAreaId]
,[DataLakeModified_DateTime]=cast([DataLakeModified_DateTime] as datetime2(0))
,[EmptyTaxBaseForOutgoingTax_W]
,[EUROTriangulation]
,[ExchRateDiffOrigRecId]
,[ExemptCode]
,[ExemptTax]
,[GSTHSTTaxType_CA]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='GSTHSTTaxType_CA' and e.EnumCode=t.[GSTHSTTaxType_CA]) ,GSTHSTTaxType_CAEnumID=[GSTHSTTaxType_CA]
,[HeadingTableId]
,[IntracomVAT]
,[InventTransId]
,[InvoiceId]
,[IsOverUnderPayment]=case when [IsOverUnderPayment]=1 then 'Yes' else 'No' end ,IsOverUnderPaymentFlag=cast([IsOverUnderPayment] as bit)
,[JournalNum]
,[MODIFIEDBY]
,[MODIFIEDDATETIME]=cast([MODIFIEDDATETIME] as date)
,[OriginTaxTransRecId]
,[PARTITION]
,[PartyTaxId]
,[PostponeVAT]
,[PrintCode]
,[RealizedDate]=cast([RealizedDate] as date)
,[Reason]
,[ReasonComment]
,[RECID]
,[RECVERSION]
,[ReverseCharge_W]
,[Source]
,[SourceBaseAmountCur]=cast([SourceBaseAmountCur] as numeric(18,2))
,[SourceBaseAmountCurRegulated]=cast([SourceBaseAmountCurRegulated] as numeric(18,2))
,[SourceCurrencyCode]
,[SourceDocumentLine]
,[SourceRecId]
,[SourceRegulateAmountCur]
,[SourceTableId]
,[SourceTaxAmountCur]=cast([SourceTaxAmountCur] as numeric(18,2))
,[statementId]
,[TaxAccountType]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxAccountingPostingAccountType' and e.EnumCode=t.[TaxAccountType]) ,TaxAccountTypeEnumID=[TaxAccountType]
,[TaxAmount]=cast([TaxAmount] as numeric(18,2))
,[TaxAmountCur]=cast([TaxAmountCur] as numeric(18,2))
,[TaxAmountRep]=cast([TaxAmountRep] as numeric(18,2))
,[TaxAutogenerated]
,[TaxBaseAmount]=cast([TaxBaseAmount] as numeric(18,2))
,[TaxBaseAmountCur]=cast([TaxBaseAmountCur] as numeric(18,2))
,[TaxBaseAmountRep]=cast([TaxBaseAmountRep] as numeric(18,2))
,[TaxBaseQty]
,[TaxBook]
,[TaxBookSection]
,[TaxCode]
,[TaxDirection]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxDirection' and e.EnumCode=t.[TaxDirection]) ,TaxDirectionEnumID=[TaxDirection]
,[TaxGroup]
,[TaxID]
,[TaxInCostPrice]=cast([TaxInCostPrice] as numeric(18,2))
,[TaxInCostPriceCur]=cast([TaxInCostPriceCur] as numeric(18,2))
,[TaxInCostPriceMST]=cast([TaxInCostPriceMST] as numeric(18,2))
,[TaxInCostPriceRegulated]
,[TaxInCostPriceRep]=cast([TaxInCostPriceRep] as numeric(18,2))
,[TaxItemGroup]
,[TaxJurisdictionCode]
,[TaxObligationCompany]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxObligationCompany' and e.EnumCode=t.[TaxObligationCompany]) ,TaxObligationCompanyEnumID=[TaxObligationCompany]
,[TaxOrigin]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxOrigin' and e.EnumCode=t.[TaxOrigin]) ,TaxOriginEnumID=[TaxOrigin]
,[TaxPeriod]
,[TaxPrintDetail]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxPrintDetail' and e.EnumCode=t.[TaxPrintDetail]) ,TaxPrintDetailEnumID=[TaxPrintDetail]
,[TaxRepCounter]
,[TaxTransRefRecId]
,[TaxType_MX]=(select top 1 e.Enum from dbo.Enum e where e.EnumSet='TaxType_MX' and e.EnumCode=t.[TaxType_MX]) ,TaxType_MXEnumID=[TaxType_MX]
,[TaxValue]=cast([TaxValue] as numeric(18,6))
,[TransDate]=cast([TransDate] as date)
,[UnrealizedTax]
,[UnrealizedTaxExt]
,[VATExemptPct]=cast([VATExemptPct] as numeric(18,6))
,[Voucher]
 from stage.TaxTrans t
GO
