CREATE EXTERNAL TABLE [blobFull].[CustTable]
(
[_SysRowId] [varchar] (60) NULL,
[LSN] [varchar] (60) NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[RECID] [bigint] NULL,
[PaymTermId] [varchar] (100) NULL,
[LineDisc] [varchar] (10) NULL,
[TaxWithholdGroup_TH] [varchar] (10) NULL,
[PartyCountry] [varchar] (10) NULL,
[AccountNum] [varchar] (20) NULL,
[AccountStatement] [varchar] (51) NULL,
[Affiliated_RU] [varchar] (51) NULL,
[AgencyLocationCode] [varchar] (12) NULL,
[BankAccount] [varchar] (10) NULL,
[BankCentralBankPurposeCode] [varchar] (10) NULL,
[BankCentralBankPurposeText] [varchar] (210) NULL,
[BankCustPaymIdTable] [bigint] NULL,
[BirthCountyCode_IT] [varchar] (2) NULL,
[BirthPlace_IT] [varchar] (120) NULL,
[Blocked] [varchar] (51) NULL,
[CashDisc] [varchar] (10) NULL,
[CashDiscBaseDays] [int] NULL,
[CCMNum_BR] [varchar] (20) NULL,
[ClearingPeriod] [varchar] (100) NULL,
[CNAE_BR] [varchar] (10) NULL,
[CNPJCPFNum_BR] [varchar] (20) NULL,
[COMMERCIALREGISTER] [varchar] (251) NULL,
[COMMERCIALREGISTERINSETNUMBER] [varchar] (251) NULL,
[COMMERCIALREGISTERSECTION] [varchar] (251) NULL,
[CommissionGroup] [varchar] (10) NULL,
[CompanyChainId] [varchar] (20) NULL,
[CompanyIdSiret] [varchar] (14) NULL,
[CompanyNAFCode] [bigint] NULL,
[CompanyType_MX] [varchar] (51) NULL,
[ConsDay_JP] [varchar] (51) NULL,
[ContactPersonId] [varchar] (20) NULL,
[CreditCardAddressVerification] [varchar] (51) NULL,
[CreditCardAddressVerificationLevel] [varchar] (51) NULL,
[CreditCardAddressVerificationVoid] [varchar] (51) NULL,
[CreditCardCVC] [varchar] (51) NULL,
[CreditMax] [varchar] (51) NULL,
[CreditRating] [varchar] (10) NULL,
[Curp_MX] [varchar] (18) NULL,
[Currency] [varchar] (3) NULL,
[CustClassificationId] [varchar] (10) NULL,
[CustExcludeCollectionFee] [varchar] (51) NULL,
[CustExcludeInterestCharges] [varchar] (51) NULL,
[CustFinalUser_BR] [varchar] (51) NULL,
[CustGroup] [varchar] (10) NULL,
[CustItemGroupId] [varchar] (10) NULL,
[CustTradingPartnerCode] [bigint] NULL,
[CustWhtContributionType_BR] [varchar] (51) NULL,
[DefaultDimension] [varchar] (51) NULL,
[DefaultDirectDebitMandate] [bigint] NULL,
[DefaultInventStatusId] [varchar] (10) NULL,
[DestinationCodeId] [varchar] (10) NULL,
[DlvMode] [varchar] (10) NULL,
[DlvReason] [varchar] (10) NULL,
[DlvTerm] [varchar] (10) NULL,
[EInvoice] [varchar] (51) NULL,
[EInvoiceAttachment] [varchar] (51) NULL,
[EinvoiceEANNum] [varchar] (13) NULL,
[EndDisc] [varchar] (10) NULL,
[EntryCertificateRequired_W] [varchar] (51) NULL,
[ExportSales_PL] [varchar] (51) NULL,
[ExpressBillOfLading] [varchar] (51) NULL,
[FactoringAccount] [varchar] (20) NULL,
[FederalComments] [varchar] (120) NULL,
[FedNonFedIndicator] [varchar] (51) NULL,
[FineCode_BR] [varchar] (10) NULL,
[FiscalCode] [varchar] (16) NULL,
[FiscalDocType_PL] [varchar] (51) NULL,
[ForecastDMPInclude] [varchar] (51) NULL,
[ForeignResident_RU] [varchar] (51) NULL,
[FreightZone] [varchar] (10) NULL,
[GenerateIncomingFiscalDocument_BR] [varchar] (51) NULL,
[GiroType] [varchar] (51) NULL,
[GiroTypeAccountStatement] [varchar] (51) NULL,
[GiroTypeCollectionletter] [varchar] (51) NULL,
[GiroTypeFreeTextInvoice] [varchar] (51) NULL,
[GiroTypeInterestNote] [varchar] (51) NULL,
[GiroTypeProjInvoice] [varchar] (51) NULL,
[ICMSContributor_BR] [varchar] (51) NULL,
[IdentificationNumber] [varchar] (50) NULL,
[IENum_BR] [varchar] (20) NULL,
[InclTax] [varchar] (51) NULL,
[INSSCEI_BR] [varchar] (15) NULL,
[IntBank_LV] [varchar] (10) NULL,
[InterCompanyAllowIndirectCreation] [varchar] (51) NULL,
[InterCompanyAutoCreateOrders] [varchar] (51) NULL,
[InterCompanyDirectDelivery] [varchar] (51) NULL,
[InterestCode_BR] [varchar] (10) NULL,
[InventLocation] [varchar] (10) NULL,
[InventProfileId_RU] [varchar] (10) NULL,
[InventProfileType_RU] [varchar] (51) NULL,
[InventSiteId] [varchar] (10) NULL,
[InvoiceAccount] [varchar] (20) NULL,
[InvoiceAddress] [varchar] (51) NULL,
[InvoicePostingType_RU] [varchar] (51) NULL,
[IRS1099CIndicator] [varchar] (51) NULL,
[IsResident_LV] [varchar] (51) NULL,
[IssueOwnEntryCertificate_W] [varchar] (51) NULL,
[IssuerCountry_HU] [varchar] (10) NULL,
[LineOfBusinessId] [varchar] (10) NULL,
[LvPaymTransCodes] [bigint] NULL,
[MainContactWorker] [bigint] NULL,
[MandatoryCreditLimit] [varchar] (51) NULL,
[MandatoryVatDate_PL] [varchar] (51) NULL,
[MarkupGroup] [varchar] (10) NULL,
[MCRMergedParent] [varchar] (20) NULL,
[MCRMergedRoot] [varchar] (20) NULL,
[MultiLineDisc] [varchar] (10) NULL,
[NIT_BR] [varchar] (14) NULL,
[numberSequenceGroup] [varchar] (10) NULL,
[OneTimeCustomer] [varchar] (51) NULL,
[OrderEntryDeadlineGroupId] [varchar] (10) NULL,
[OrgId] [varchar] (10) NULL,
[OurAccountNum] [varchar] (20) NULL,
[PackageDepositExcempt_PL] [varchar] (51) NULL,
[PackMaterialFeeLicenseNum] [varchar] (20) NULL,
[Party] [bigint] NULL,
[PartyState] [varchar] (10) NULL,
[PassportNo_HU] [varchar] (13) NULL,
[PaymDayId] [varchar] (10) NULL,
[PaymentReference_EE] [varchar] (35) NULL,
[PaymIdType] [varchar] (10) NULL,
[PaymMode] [varchar] (10) NULL,
[PaymSched] [varchar] (30) NULL,
[PaymSpec] [varchar] (10) NULL,
[PdsCustRebateGroupId] [varchar] (20) NULL,
[PdsFreightAccrued] [varchar] (51) NULL,
[PdsRebateTMAGroup] [varchar] (10) NULL,
[PriceGroup] [varchar] (10) NULL,
[ResidenceForeignCountryRegionId_IT] [varchar] (10) NULL,
[Rfc_MX] [varchar] (13) NULL,
[RFIDCASETAGGING] [int] NULL,
[RFIDITEMTAGGING] [int] NULL,
[RFIDPALLETTAGGING] [int] NULL,
[SalesCalendarId] [varchar] (10) NULL,
[SalesDistrictId] [varchar] (20) NULL,
[SalesGroup] [varchar] (10) NULL,
[SalesPoolId] [varchar] (10) NULL,
[SegmentId] [varchar] (20) NULL,
[ServiceCodeOnDlvAddress_BR] [varchar] (51) NULL,
[ShipCarrierAccount] [varchar] (25) NULL,
[ShipCarrierAccountCode] [varchar] (20) NULL,
[ShipCarrierBlindShipment] [varchar] (51) NULL,
[ShipCarrierFuelSurcharge] [varchar] (51) NULL,
[ShipCarrierId] [varchar] (10) NULL,
[StateInscription_MX] [varchar] (30) NULL,
[StatisticsGroup] [varchar] (10) NULL,
[SubsegmentId] [varchar] (20) NULL,
[Suframa_BR] [varchar] (51) NULL,
[SuframaNumber_BR] [varchar] (10) NULL,
[SuframaPISCOFINS_BR] [varchar] (51) NULL,
[SuppItemGroupId] [varchar] (10) NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxLicenseNum] [varchar] (20) NULL,
[TaxPeriodPaymentCode_PL] [varchar] (10) NULL,
[TaxWithholdCalculate_IN] [varchar] (51) NULL,
[TaxWithholdCalculate_TH] [varchar] (51) NULL,
[UnitedVATInvoice_LT] [varchar] (51) NULL,
[UseCashDisc] [varchar] (51) NULL,
[usePurchRequest] [varchar] (51) NULL,
[VATNum] [varchar] (20) NULL,
[VendAccount] [varchar] (20) NULL,
[WebSalesOrderDisplay] [varchar] (51) NULL,
[AuthorityOffice_IT] [varchar] (7) NULL,
[EInvoiceRegister_IT] [varchar] (51) NULL,
[ForeignerId_BR] [varchar] (20) NULL,
[PresenceType_BR] [varchar] (51) NULL,
[TaxGSTReliefGroupHeading_MY] [bigint] NULL,
[ForeignTaxRegistration_MX] [varchar] (40) NULL,
[CustWriteOffRefRecId] [bigint] NULL,
[IsExternallyMaintained] [varchar] (51) NULL,
[SATPaymMethod_MX] [varchar] (10) NULL,
[SATPurpose_MX] [varchar] (10) NULL,
[CFDIEnabled_MX] [varchar] (51) NULL,
[ForeignTrade_MX] [varchar] (51) NULL,
[WorkflowState] [varchar] (51) NULL,
[UseOriginalDocumentAsFacture_RU] [varchar] (51) NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CollectionLetterCode] [varchar] (51) NULL,
[BlockFloorLimitUseInChannel] [varchar] (51) NULL,
[CFDISkipIEPSTaxes_MX] [varchar] (51) NULL,
[SimplifyTaxIntgrExportDocValidation_CN] [varchar] (51) NULL,
[RevRecDisableIntercompany] [varchar] (51) NULL,
[FreeNotesGroup_IT] [varchar] (10) NULL,
[UsualExporter_IT] [varchar] (51) NULL,
[CredManEligibleCreditLimitDate] [varchar] (40) NULL,
[CredManGroupId] [varchar] (10) NULL,
[CredManExclude] [varchar] (51) NULL,
[CredManAccountStatusId] [varchar] (30) NULL,
[CredManEligibleCreditMax] [varchar] (51) NULL,
[CredManBusinessStarted] [varchar] (40) NULL,
[CredManTitleHeld] [varchar] (51) NULL,
[CredManCustCreditMaxAlt] [varchar] (51) NULL,
[CredManEligibleCreditLimitCurrency] [varchar] (3) NULL,
[CredManCustomerSince] [varchar] (40) NULL,
[CredManWithAgency] [varchar] (51) NULL,
[CredManStatusReasonId] [varchar] (10) NULL,
[CredManCollectionGroupId] [varchar] (10) NULL,
[CredManCreditLimitExpiryDate] [varchar] (40) NULL,
[CredManCreditLimitDate] [varchar] (40) NULL,
[CredManLastReviewDate] [varchar] (40) NULL,
[CredManNextSchedReviewDate] [varchar] (40) NULL,
[CredManCustUnlimitedCredit] [varchar] (51) NULL,
[SimpleNational_BR] [varchar] (51) NULL,
[IsPublicSector_IT] [varchar] (51) NULL,
[PrintDynamicQRCode_IN] [varchar] (51) NULL,
[VATNumRecId] [bigint] NULL,
[VATNumTableType] [varchar] (51) NULL,
[SimplifyTaxIntgrExportTaxRegValidation_CN] [varchar] (51) NULL,
[InvoiceType_W] [varchar] (51) NULL,
[OverrideSalesTax] [varchar] (51) NULL,
[TaxRegimeCode_MX] [varchar] (10) NULL,
[CFDITemporaryExport_MX] [varchar] (51) NULL,
[SATRegistrationName_MX] [varchar] (300) NULL
)
WITH
(
LOCATION = N'Tables/Common/Customer/Main/CustTable/*.csv',
DATA_SOURCE = [d365ADLS],
FILE_FORMAT = [csvQuotedText],
REJECT_TYPE = value,
REJECT_VALUE = 0
)
GO
