CREATE EXTERNAL TABLE [blobFull].[VendInvoiceJour]
(
[_SysRowId] [varchar] (60) NULL,
[LSN] [varchar] (60) NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[RECID] [bigint] NULL,
[OrderAccount] [varchar] (20) NULL,
[AttorneyDate_RU] [varchar] (40) NULL,
[AttorneyId_RU] [varchar] (30) NULL,
[AttorneyIssuedName_RU] [varchar] (30) NULL,
[BankLCImportLine] [bigint] NULL,
[CashDisc] [varchar] (51) NULL,
[CashDiscCode] [varchar] (10) NULL,
[CashDiscDate] [varchar] (40) NULL,
[CashDiscPercent] [varchar] (51) NULL,
[ConsigneeAccount_RU] [varchar] (20) NULL,
[ConsignorAccount_RU] [varchar] (20) NULL,
[ConsTarget_JP] [varchar] (51) NULL,
[ContractNum_SA] [varchar] (60) NULL,
[Correct_RU] [varchar] (51) NULL,
[CorrectedInvoiceDate_RU] [varchar] (40) NULL,
[CorrectedInvoiceId_RU] [varchar] (30) NULL,
[CorrectionType_RU] [varchar] (51) NULL,
[CostLedgerVoucher] [varchar] (30) NULL,
[CountryRegionId] [varchar] (10) NULL,
[CurrencyCode] [varchar] (3) NULL,
[DefaultDimension] [bigint] NULL,
[DeliveryAddress_LT] [varchar] (250) NULL,
[DeliveryDate_ES] [varchar] (40) NULL,
[DeliveryName] [varchar] (100) NULL,
[DeliveryName_LT] [varchar] (100) NULL,
[DeliveryPostalAddress] [bigint] NULL,
[Description] [varchar] (255) NULL,
[DlvAddress_LV] [varchar] (250) NULL,
[DlvMode] [varchar] (10) NULL,
[DlvTerm] [varchar] (10) NULL,
[DocumentDate] [varchar] (40) NULL,
[DocumentNum] [varchar] (20) NULL,
[DocumentOrigin] [varchar] (51) NULL,
[DueDate] [varchar] (40) NULL,
[EndDisc] [varchar] (51) NULL,
[EndDiscMST] [varchar] (51) NULL,
[EnterpriseNumber] [varchar] (50) NULL,
[EUSalesList] [varchar] (30) NULL,
[ExchRate] [varchar] (51) NULL,
[ExchRateSecondary] [varchar] (51) NULL,
[FacturedFully_RU] [varchar] (51) NULL,
[FiscalDocumentType_BR] [bigint] NULL,
[FixedDueDate] [varchar] (40) NULL,
[InclTax] [varchar] (51) NULL,
[InterCompanyCompanyId] [varchar] (4) NULL,
[InterCompanyLedgerVoucher] [varchar] (30) NULL,
[InterCompanyPosted] [varchar] (51) NULL,
[InterCompanySalesId] [varchar] (30) NULL,
[InternalInvoiceId] [varchar] (30) NULL,
[IntrastatAddValue_LV] [float] NULL,
[IntrastatDispatch] [varchar] (30) NULL,
[IntrastatFulfillmentDate_HU] [varchar] (40) NULL,
[InventBaileeReceiptReportId_RU] [varchar] (30) NULL,
[InventProfileType_RU] [varchar] (51) NULL,
[InvoiceAccount] [varchar] (20) NULL,
[InvoiceAmount] [float] NULL,
[InvoiceAmountMST] [float] NULL,
[InvoiceDate] [varchar] (40) NULL,
[InvoiceId] [varchar] (30) NULL,
[InvoiceRoundOff] [float] NULL,
[InvoiceType] [varchar] (51) NULL,
[ItemBuyerGroupId] [varchar] (10) NULL,
[LanguageId] [varchar] (7) NULL,
[LedgerVoucher] [varchar] (30) NULL,
[Listcode] [varchar] (51) NULL,
[LogisticsElectronicAddress] [bigint] NULL,
[NonRealRevenue_RU] [varchar] (51) NULL,
[NumberSequenceCode_LT] [varchar] (10) NULL,
[numberSequenceGroup] [varchar] (10) NULL,
[OffsessionId_RU] [varchar] (30) NULL,
[OperationType_MX] [varchar] (51) NULL,
[ParmId] [varchar] (30) NULL,
[PaymDayId] [varchar] (10) NULL,
[Payment] [varchar] (100) NULL,
[PaymentSched] [varchar] (30) NULL,
[PaymId] [varchar] (200) NULL,
[PostingProfile] [varchar] (10) NULL,
[Prepayment] [varchar] (51) NULL,
[Proforma] [varchar] (51) NULL,
[PurchAgreementHeader_PSN] [bigint] NULL,
[PurchaseType] [varchar] (51) NULL,
[PurchId] [varchar] (30) NULL,
[PurchReceiptDate_W] [varchar] (40) NULL,
[Qty] [varchar] (51) NULL,
[ReasonTableRef_BR] [bigint] NULL,
[RemittanceAddress] [bigint] NULL,
[ReturnItemNum] [varchar] (10) NULL,
[ReverseChargeAmount] [float] NULL,
[SalesBalance] [float] NULL,
[SalesPurchOperationType_BR] [bigint] NULL,
[ServiceCodeOnDlvAddress_BR] [varchar] (51) NULL,
[SourceDocumentHeader] [bigint] NULL,
[SourceDocumentLine] [bigint] NULL,
[StateInvoicePrinted_LV] [varchar] (51) NULL,
[SumLineDisc] [varchar] (51) NULL,
[SumMarkup] [varchar] (51) NULL,
[SumMarkupMST] [float] NULL,
[SumTax] [float] NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxInvoicePurchId] [varchar] (30) NULL,
[TaxPrintOnInvoice] [varchar] (51) NULL,
[TaxRoundOff] [float] NULL,
[TaxSetoffVoucher_IN] [varchar] (30) NULL,
[TaxSpecifyByLine] [varchar] (51) NULL,
[TaxWithholdAmount_IN] [float] NULL,
[TransportationDocument] [bigint] NULL,
[Triangulation] [varchar] (51) NULL,
[UnitedVATInvoice_LT] [varchar] (51) NULL,
[VATAmount_IN] [float] NULL,
[VATNum] [varchar] (20) NULL,
[VATOnPayment_RU] [varchar] (51) NULL,
[VendConsInvoice_JP] [bigint] NULL,
[VendFinalUser_BR] [varchar] (51) NULL,
[VendGroup] [varchar] (10) NULL,
[VendInvoiceDeclaration_IS] [bigint] NULL,
[VendInvoiceGroup] [varchar] (10) NULL,
[VendorRequestedWorkerEmail] [varchar] (80) NULL,
[VendPaymentGroup] [varchar] (10) NULL,
[Volume] [varchar] (51) NULL,
[Weight] [varchar] (51) NULL,
[WhoIsAuthor_LT] [varchar] (51) NULL,
[CFDIUUID_MX] [varchar] (36) NULL,
[InvoiceSeries_MX] [varchar] (10) NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[ReportingCurrencyExchangeRate] [varchar] (51) NULL,
[PSNPurchasingCardType] [varchar] (51) NULL,
[IntentLetterId_IT] [varchar] (10) NULL,
[PlafondDate_IT] [varchar] (40) NULL,
[ImportedSalesTax] [varchar] (51) NULL,
[ReceivedDate] [varchar] (40) NULL,
[ImportedAmount] [float] NULL,
[TaxID] [bigint] NULL,
[PartyTaxID] [bigint] NULL,
[State] [varchar] (10) NULL,
[VendorVATDate] [varchar] (40) NULL
)
WITH
(
LOCATION = N'Tables/Finance/AccountsPayable/Transaction/VendInvoiceJour/*.csv',
DATA_SOURCE = [d365ADLS],
FILE_FORMAT = [csvQuotedText],
REJECT_TYPE = value,
REJECT_VALUE = 0
)
GO
