CREATE EXTERNAL TABLE [blobFull].[SAB_ConsWorkOrderLineHistory]
(
[_SysRowId] [varchar] (60) NULL,
[LSN] [varchar] (60) NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[RECID] [bigint] NULL,
[ChangedBy] [bigint] NULL,
[ChangeReason] [bigint] NULL,
[CostCategory] [bigint] NULL,
[CSRequestLine] [bigint] NULL,
[DesignCenterAttributeChanged] [varchar] (51) NULL,
[EntryType] [varchar] (51) NULL,
[FinancialInstance] [bigint] NULL,
[InventUnit] [varchar] (10) NULL,
[ItemId] [varchar] (20) NULL,
[LineAmount] [varchar] (51) NULL,
[LineNumber] [bigint] NULL,
[LineType] [varchar] (51) NULL,
[Location] [bigint] NULL,
[LocationGroup] [bigint] NULL,
[Name] [varchar] (1000) NULL,
[NoteChanged] [varchar] (51) NULL,
[OPTION_] [bigint] NULL,
[Orientation] [varchar] (51) NULL,
[PurchPrice] [varchar] (51) NULL,
[PurchQty] [varchar] (51) NULL,
[PurchUnit] [varchar] (10) NULL,
[QtyOrdered] [varchar] (51) NULL,
[SupplementAmount] [float] NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TaxGroup] [varchar] (10) NULL,
[ValidFrom] [varchar] (40) NULL,
[VALIDFROMTZID] [int] NULL,
[ValidTo] [varchar] (40) NULL,
[VALIDTOTZID] [int] NULL,
[WorkOrder] [bigint] NULL,
[WorkOrderLine] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[DesignCenterAttributeDateTime] [varchar] (40) NULL,
[DESIGNCENTERATTRIBUTEDATETIMETZID] [int] NULL,
[Vendor] [bigint] NULL,
[EquipRentalEstimatedEndDate] [varchar] (40) NULL,
[EquipRentalStartDate] [varchar] (40) NULL,
[TradeType] [bigint] NULL
)
WITH
(
LOCATION = N'Tables/SAB_ConsProcurement/Transaction/SAB_ConsWorkOrderLineHistory/*.csv',
DATA_SOURCE = [d365ADLS],
FILE_FORMAT = [csvQuotedText],
REJECT_TYPE = value,
REJECT_VALUE = 0
)
GO
