CREATE EXTERNAL TABLE [blobFull].[BankAccountTrans]
(
[_SysRowId] [varchar] (60) NULL,
[LSN] [varchar] (60) NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[RECID] [bigint] NULL,
[CurrencyCode] [varchar] (3) NULL,
[AccountId] [varchar] (10) NULL,
[AccountingCurrencyAmountCorrect_RU] [float] NULL,
[AccountStatement] [varchar] (20) NULL,
[AccountStatementDate] [varchar] (40) NULL,
[AcknowledgementDate] [varchar] (40) NULL,
[AmountCorrect] [float] NULL,
[AmountCur] [float] NULL,
[AmountMST] [float] NULL,
[BankPaymentRegistrationNum_LV] [varchar] (20) NULL,
[BankTransAmountCur] [float] NULL,
[BankTransCurrencyCode] [varchar] (3) NULL,
[BankTransType] [varchar] (10) NULL,
[Cancel] [varchar] (51) NULL,
[CancelPending] [varchar] (51) NULL,
[CentralBankPurposeCode_LV] [varchar] (10) NULL,
[CentralBankPurposeText_LV] [varchar] (210) NULL,
[ChequeNum] [varchar] (20) NULL,
[CorrespondentCountry_LV] [varchar] (10) NULL,
[DefaultDimension] [varchar] (51) NULL,
[DepositNum] [varchar] (30) NULL,
[Included] [varchar] (51) NULL,
[LedgerDimension] [varchar] (51) NULL,
[LedgerTransType] [varchar] (51) NULL,
[Manual] [varchar] (51) NULL,
[PaymentMode] [varchar] (10) NULL,
[PaymReference] [varchar] (35) NULL,
[ReasonRefRecID] [bigint] NULL,
[Reconciled] [varchar] (51) NULL,
[RefRecId_RU] [bigint] NULL,
[ReportingCurrencyAmount_RU] [float] NULL,
[ReportingCurrencyAmountCorrect_RU] [float] NULL,
[SourceRecId] [bigint] NULL,
[SourceTableId] [varchar] (51) NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TransDate] [varchar] (40) NULL,
[Txt] [varchar] (512) NULL,
[Voucher] [varchar] (30) NULL,
[AmountReportingCurrency] [float] NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[ClearedDate] [varchar] (40) NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL
)
WITH
(
LOCATION = N'Tables/Finance/Bank/Transaction/BankAccountTrans/*.csv',
DATA_SOURCE = [d365ADLS],
FILE_FORMAT = [csvQuotedText],
REJECT_TYPE = value,
REJECT_VALUE = 0
)
GO
