CREATE EXTERNAL TABLE [blobFull].[SAB_ConsLotTable]
(
[_SysRowId] [varchar] (60) NULL,
[LSN] [varchar] (60) NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[RECID] [bigint] NULL,
[ACCRUED] [int] NULL,
[BuildingTypeId] [varchar] (20) NULL,
[CLOSED] [int] NULL,
[ColorScheme] [bigint] NULL,
[CostPrice] [float] NULL,
[CSAccrualGroup] [bigint] NULL,
[Description] [varchar] (120) NULL,
[DevelopmentId] [varchar] (10) NULL,
[FacadeId] [varchar] (20) NULL,
[FINALIZED] [int] NULL,
[HasTitle] [varchar] (51) NULL,
[Location] [bigint] NULL,
[LotNo] [varchar] (30) NULL,
[LotStatusId] [varchar] (10) NULL,
[LotStructureElement] [bigint] NULL,
[Orientation] [varchar] (51) NULL,
[Ownership] [varchar] (51) NULL,
[PHASERELEASEID] [varchar] (251) NULL,
[RELEASEGROUP] [bigint] NULL,
[SalesPerson] [bigint] NULL,
[SalesPrice] [float] NULL,
[SalesPriceBase] [float] NULL,
[SalesPriceDiscount] [float] NULL,
[SalesPriceOption] [float] NULL,
[StockStatus] [varchar] (20) NULL,
[Subfloor] [bigint] NULL,
[TitleDate] [varchar] (40) NULL,
[Tract] [varchar] (10) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[FINALIZATIONSTATUS] [int] NULL,
[BuyerOwned] [varchar] (51) NULL,
[JobType] [bigint] NULL,
[TarionEnrolmentNumber] [varchar] (10) NULL,
[SalesPriceLotPremium] [float] NULL,
[PriceLocked] [varchar] (51) NULL,
[PriceLockedAsOf] [varchar] (40) NULL,
[PRICELOCKEDASOFTZID] [int] NULL,
[PriceLockedBy] [bigint] NULL,
[LotPremiumInventory] [float] NULL,
[OH_ConsLotPhase] [varchar] (10) NULL,
[OH_LotOwnershipType] [varchar] (50) NULL,
[OH_LotMigrated] [varchar] (51) NULL,
[OH_ExternalSalesPrice] [float] NULL
)
WITH
(
LOCATION = N'Tables/SAB_ConsLandDevelopment/Main/SAB_ConsLotTable/*.csv',
DATA_SOURCE = [d365ADLS],
FILE_FORMAT = [csvQuotedText],
REJECT_TYPE = value,
REJECT_VALUE = 0
)
GO
