CREATE TABLE [dbo].[VendInvoiceJour]
(
[AttorneyDate_RU] [date] NULL,
[AttorneyId_RU] [varchar] (30) NULL,
[AttorneyIssuedName_RU] [varchar] (30) NULL,
[BankLCImportLine] [bigint] NULL,
[CashDisc] [varchar] (51) NULL,
[CashDiscCode] [varchar] (10) NULL,
[CashDiscDate] [date] NULL,
[CashDiscPercent] [varchar] (51) NULL,
[CFDIUUID_MX] [varchar] (36) NULL,
[ConsigneeAccount_RU] [varchar] (20) NULL,
[ConsignorAccount_RU] [varchar] (20) NULL,
[ConsTarget_JP] [varchar] (51) NULL,
[ContractNum_SA] [varchar] (60) NULL,
[Correct_RU] [varchar] (51) NULL,
[CorrectedInvoiceDate_RU] [date] NULL,
[CorrectedInvoiceId_RU] [varchar] (30) NULL,
[CorrectionType_RU] [varchar] (256) NULL,
[CorrectionType_RUEnumID] [varchar] (51) NULL,
[CostLedgerVoucher] [varchar] (30) NULL,
[CountryRegionId] [varchar] (10) NULL,
[CREATEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [date] NULL,
[CurrencyCode] [varchar] (3) NULL,
[DataAreaId] [varchar] (4) NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DefaultDimension] [bigint] NULL,
[DeliveryAddress_LT] [varchar] (250) NULL,
[DeliveryDate_ES] [date] NULL,
[DeliveryName] [varchar] (100) NULL,
[DeliveryName_LT] [varchar] (100) NULL,
[DeliveryPostalAddress] [bigint] NULL,
[Description] [varchar] (255) NULL,
[DlvAddress_LV] [varchar] (250) NULL,
[DlvMode] [varchar] (10) NULL,
[DlvTerm] [varchar] (10) NULL,
[DocumentDate] [date] NULL,
[DocumentNum] [varchar] (20) NULL,
[DocumentOrigin] [varchar] (256) NULL,
[DocumentOriginEnumID] [varchar] (51) NULL,
[DueDate] [date] NULL,
[EndDisc] [varchar] (51) NULL,
[EndDiscMST] [varchar] (51) NULL,
[EnterpriseNumber] [varchar] (50) NULL,
[EUSalesList] [varchar] (30) NULL,
[ExchRate] [varchar] (51) NULL,
[ExchRateSecondary] [varchar] (51) NULL,
[FacturedFully_RU] [varchar] (51) NULL,
[FiscalDocumentType_BR] [bigint] NULL,
[FixedDueDate] [date] NULL,
[ImportedAmount] [numeric] (18, 2) NULL,
[ImportedSalesTax] [varchar] (51) NULL,
[InclTax] [varchar] (51) NULL,
[IntentLetterId_IT] [varchar] (10) NULL,
[InterCompanyCompanyId] [varchar] (4) NULL,
[InterCompanyLedgerVoucher] [varchar] (30) NULL,
[InterCompanyPosted] [varchar] (51) NULL,
[InterCompanySalesId] [varchar] (30) NULL,
[InternalInvoiceId] [varchar] (30) NULL,
[IntrastatAddValue_LV] [numeric] (18, 2) NULL,
[IntrastatDispatch] [varchar] (30) NULL,
[IntrastatFulfillmentDate_HU] [date] NULL,
[InventBaileeReceiptReportId_RU] [varchar] (30) NULL,
[InventProfileType_RU] [varchar] (256) NULL,
[InventProfileType_RUEnumID] [varchar] (51) NULL,
[InvoiceAccount] [varchar] (20) NULL,
[InvoiceAmount] [numeric] (18, 2) NULL,
[InvoiceAmountMST] [numeric] (18, 2) NULL,
[InvoiceDate] [date] NULL,
[InvoiceId] [varchar] (30) NULL,
[InvoiceRoundOff] [numeric] (18, 2) NULL,
[InvoiceSeries_MX] [varchar] (10) NULL,
[InvoiceType] [varchar] (256) NULL,
[InvoiceTypeEnumID] [varchar] (51) NULL,
[ItemBuyerGroupId] [varchar] (10) NULL,
[LanguageId] [varchar] (7) NULL,
[LedgerVoucher] [varchar] (30) NULL,
[Listcode] [varchar] (51) NULL,
[LogisticsElectronicAddress] [bigint] NULL,
[MODIFIEDDATETIME] [date] NULL,
[NonRealRevenue_RU] [varchar] (51) NULL,
[NumberSequenceCode_LT] [varchar] (10) NULL,
[numberSequenceGroup] [varchar] (10) NULL,
[OffsessionId_RU] [varchar] (30) NULL,
[OperationType_MX] [varchar] (256) NULL,
[OperationType_MXEnumID] [varchar] (51) NULL,
[OrderAccount] [varchar] (20) NULL,
[ParmId] [varchar] (30) NULL,
[PARTITION] [bigint] NULL,
[PartyTaxID] [bigint] NULL,
[PaymDayId] [varchar] (10) NULL,
[Payment] [varchar] (100) NULL,
[PaymentSched] [varchar] (30) NULL,
[PaymId] [varchar] (200) NULL,
[PlafondDate_IT] [date] NULL,
[PostingProfile] [varchar] (10) NULL,
[Prepayment] [varchar] (51) NULL,
[Proforma] [varchar] (51) NULL,
[PSNPurchasingCardType] [varchar] (256) NULL,
[PSNPurchasingCardTypeEnumID] [varchar] (51) NULL,
[PurchAgreementHeader_PSN] [bigint] NULL,
[PurchaseType] [varchar] (256) NULL,
[PurchaseTypeEnumID] [varchar] (51) NULL,
[PurchId] [varchar] (30) NULL,
[PurchReceiptDate_W] [date] NULL,
[Qty] [varchar] (51) NULL,
[ReasonTableRef_BR] [bigint] NULL,
[ReceivedDate] [date] NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[RemittanceAddress] [bigint] NULL,
[ReportingCurrencyExchangeRate] [varchar] (51) NULL,
[ReturnItemNum] [varchar] (10) NULL,
[ReverseChargeAmount] [numeric] (18, 2) NULL,
[SalesBalance] [numeric] (18, 2) NULL,
[SalesPurchOperationType_BR] [bigint] NULL,
[ServiceCodeOnDlvAddress_BR] [varchar] (51) NULL,
[SourceDocumentHeader] [bigint] NULL,
[SourceDocumentLine] [bigint] NULL,
[State] [varchar] (10) NULL,
[StateInvoicePrinted_LV] [varchar] (3) NULL,
[StateInvoicePrinted_LVFlag] [bit] NULL,
[SumLineDisc] [varchar] (51) NULL,
[SumMarkup] [varchar] (51) NULL,
[SumMarkupMST] [numeric] (18, 2) NULL,
[SumTax] [numeric] (18, 2) NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxID] [bigint] NULL,
[TaxInvoicePurchId] [varchar] (30) NULL,
[TaxPrintOnInvoice] [varchar] (51) NULL,
[TaxRoundOff] [numeric] (18, 2) NULL,
[TaxSetoffVoucher_IN] [varchar] (30) NULL,
[TaxSpecifyByLine] [varchar] (51) NULL,
[TaxWithholdAmount_IN] [numeric] (18, 2) NULL,
[TransportationDocument] [bigint] NULL,
[Triangulation] [varchar] (51) NULL,
[UnitedVATInvoice_LT] [varchar] (51) NULL,
[VATAmount_IN] [numeric] (18, 2) NULL,
[VATNum] [varchar] (20) NULL,
[VATOnPayment_RU] [varchar] (51) NULL,
[VendConsInvoice_JP] [bigint] NULL,
[VendFinalUser_BR] [varchar] (51) NULL,
[VendGroup] [varchar] (10) NULL,
[VendInvoiceDeclaration_IS] [bigint] NULL,
[VendInvoiceGroup] [varchar] (10) NULL,
[VendorRequestedWorkerEmail] [varchar] (80) NULL,
[VendorVATDate] [date] NULL,
[VendPaymentGroup] [varchar] (10) NULL,
[Volume] [numeric] (18, 6) NULL,
[Weight] [varchar] (51) NULL,
[WhoIsAuthor_LT] [varchar] (256) NULL,
[WhoIsAuthor_LTEnumID] [varchar] (51) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VendInvoiceJour] ADD CONSTRAINT [PK_VendInvoiceJour_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_dbo_NC_VendInvoiceJour] ON [dbo].[VendInvoiceJour] ([InvoiceDate], [LedgerVoucher]) ON [PRIMARY]
GO
