CREATE TABLE [dbo].[SysUserInfo]
(
[AutomaticUrlUpdate] [varchar] (51) NULL,
[compilerTarget] [varchar] (256) NULL,
[compilerTargetEnumID] [varchar] (51) NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DefaultCountryRegion] [varchar] (10) NULL,
[defaultExcelExportPath] [varchar] (255) NULL,
[defaultExcelExportSite] [varchar] (255) NULL,
[Density] [varchar] (256) NULL,
[DensityEnumID] [varchar] (51) NULL,
[docuHandlingActive] [varchar] (51) NULL,
[DOCUTOOLBARBUTTONACTIVE] [int] NULL,
[Email] [varchar] (80) NULL,
[EnhancedTabSequence] [varchar] (3) NULL,
[EnhancedTabSequenceFlag] [bit] NULL,
[EventEmailAlertsWhen] [varchar] (256) NULL,
[EventEmailAlertsWhenEnumID] [varchar] (51) NULL,
[EventPollFrequency] [int] NULL,
[EventPopUpDisplayWhen] [varchar] (256) NULL,
[EventPopUpDisplayWhenEnumID] [varchar] (51) NULL,
[EventPopUpLinkDestination] [varchar] (51) NULL,
[EventPopUps] [varchar] (51) NULL,
[EventWorkflowAlternateEmail] [varchar] (80) NULL,
[EventWorkflowShowPopup] [varchar] (3) NULL,
[EventWorkflowShowPopupFlag] [bit] NULL,
[EventWorkflowTasksInActionCenter] [varchar] (3) NULL,
[EventWorkflowTasksInActionCenterFlag] [bit] NULL,
[EventWorkflowTasksInClient] [varchar] (3) NULL,
[EventWorkflowTasksInClientFlag] [bit] NULL,
[EventWorkflowTasksInEmail] [varchar] (3) NULL,
[EventWorkflowTasksInEmailFlag] [bit] NULL,
[HelpMarkEmptyLinks] [varchar] (3) NULL,
[HelpMarkEmptyLinksFlag] [bit] NULL,
[HelpTheme] [varchar] (120) NULL,
[Id] [varchar] (20) NULL,
[Language] [varchar] (7) NULL,
[Mailer] [varchar] (10) NULL,
[NegativeAmountsInRed_CN] [varchar] (51) NULL,
[OH_DevUser] [varchar] (51) NULL,
[OH_SandboxUser] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[ShowTaskListOnDefaultDashboard] [varchar] (3) NULL,
[ShowTaskListOnDefaultDashboardFlag] [bit] NULL,
[SqmEnabled] [varchar] (256) NULL,
[SqmEnabledEnumID] [varchar] (51) NULL,
[SqmUserGuid] [varchar] (50) NULL,
[StartPage] [varchar] (60) NULL,
[Theme] [varchar] (256) NULL,
[ThemeEnumID] [varchar] (51) NULL,
[TooltipOnFocus] [varchar] (3) NULL,
[TooltipOnFocusFlag] [bit] NULL,
[WorkflowLineItemNotificationFormat] [varchar] (256) NULL,
[WorkflowLineItemNotificationFormatEnumID] [varchar] (51) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SysUserInfo] ADD CONSTRAINT [PK_SysUserInfo_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
