CREATE TABLE [dbo].[VendSettlement]
(
[AccountNum] [varchar] (20) NULL,
[CanBeReversed] [varchar] (51) NULL,
[CashDiscountLedgerDimension] [varchar] (51) NULL,
[ClosedDate] [date] NULL,
[CREATEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [date] NULL,
[DataAreaId] [varchar] (4) NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DefaultDimension] [bigint] NULL,
[DueDate] [date] NULL,
[EUSalesList] [varchar] (30) NULL,
[ExchAdjustment] [varchar] (51) NULL,
[ExchAdjustmentReporting] [varchar] (51) NULL,
[FineAmount_BR] [numeric] (18, 2) NULL,
[FineCode_BR] [varchar] (10) NULL,
[InterestAmount_BR] [numeric] (18, 2) NULL,
[InterestCode_BR] [varchar] (10) NULL,
[LastInterestDateDummy] [date] NULL,
[OffsetAccountNum] [varchar] (20) NULL,
[OffsetCompany] [varchar] (4) NULL,
[OffsetRecid] [bigint] NULL,
[OffsetTransVoucher] [varchar] (30) NULL,
[PARTITION] [bigint] NULL,
[PennyDiff] [numeric] (18, 2) NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[RemittanceAddress] [bigint] NULL,
[ReportingDate_RU] [date] NULL,
[ReversedRecId_RU] [bigint] NULL,
[ReverseTrans_RU] [varchar] (51) NULL,
[SettleAmountCur] [numeric] (18, 2) NULL,
[SettleAmountMST] [numeric] (18, 2) NULL,
[SettleAmountReporting] [numeric] (18, 2) NULL,
[SettlementGroup] [bigint] NULL,
[SettlementVoucher] [varchar] (30) NULL,
[SettleTax1099Amount] [varchar] (51) NULL,
[SettleTax1099StateAmount] [varchar] (51) NULL,
[StatusVoucher] [varchar] (30) NULL,
[TaxVoucher_RU] [varchar] (30) NULL,
[ThirdPartyBankAccountId] [varchar] (10) NULL,
[TransCompany] [varchar] (4) NULL,
[TransDate] [date] NULL,
[TransOpen] [bigint] NULL,
[TransRecId] [bigint] NULL,
[TransType] [varchar] (256) NULL,
[TransTypeEnumID] [varchar] (51) NULL,
[UtilizedCashDisc] [numeric] (18, 2) NULL,
[VATTaxAgentAmount_RU] [numeric] (18, 2) NULL,
[VendCashDiscDate] [date] NULL,
[VendPaymentGroup] [varchar] (10) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VendSettlement] ADD CONSTRAINT [PK_VendSettlement_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_dbo_NC_VendSettlement] ON [dbo].[VendSettlement] ([TransRecId]) ON [PRIMARY]
GO
