CREATE TABLE [dbo].[MainAccount]
(
[AccountCategoryRef] [int] NULL,
[AdjustmentMethod_MX] [varchar] (256) NULL,
[AdjustmentMethod_MXEnumID] [varchar] (51) NULL,
[CloseType] [varchar] (256) NULL,
[CloseTypeEnumID] [varchar] (51) NULL,
[Closing] [varchar] (256) NULL,
[ClosingEnumID] [varchar] (51) NULL,
[ConsolidationMainAccount] [varchar] (10) NULL,
[CREATEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [date] NULL,
[CurrencyCode] [varchar] (3) NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DebitCreditBalanceDemand] [varchar] (51) NULL,
[DebitCreditCheck] [varchar] (256) NULL,
[DebitCreditCheckEnumID] [varchar] (51) NULL,
[DebitCreditProposal] [varchar] (256) NULL,
[DebitCreditProposalEnumID] [varchar] (51) NULL,
[ExchangeAdjusted] [varchar] (3) NULL,
[ExchangeAdjustedFlag] [bit] NULL,
[ExchangeAdjustmentRateType] [varchar] (51) NULL,
[FinancialReportingExchangeRateType] [varchar] (51) NULL,
[FinancialReportingTranslationType] [varchar] (256) NULL,
[FinancialReportingTranslationTypeEnumID] [varchar] (51) NULL,
[InflationAdjustment_MX] [varchar] (51) NULL,
[LedgerChartOfAccounts] [bigint] NULL,
[MainAccountId] [varchar] (20) NULL,
[MainAccountTemplate] [bigint] NULL,
[MandatoryPaymentReference] [varchar] (3) NULL,
[MandatoryPaymentReferenceFlag] [bit] NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[MODIFIEDDATETIME] [date] NULL,
[Monetary] [varchar] (51) NULL,
[Name] [varchar] (60) NULL,
[OffsetLedgerDimension] [varchar] (51) NULL,
[OpeningAccount] [bigint] NULL,
[ParentMainAccount] [bigint] NULL,
[PARTITION] [bigint] NULL,
[PostingType] [varchar] (256) NULL,
[PostingTypeEnumID] [varchar] (51) NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[RepomoType_MX] [varchar] (256) NULL,
[RepomoType_MXEnumID] [varchar] (51) NULL,
[ReportingAccountType] [varchar] (256) NULL,
[ReportingAccountTypeEnumID] [varchar] (51) NULL,
[ReportingExchangeAdjustmentRateType] [varchar] (51) NULL,
[SRUCode] [varchar] (4) NULL,
[StandardMainAccount_W] [bigint] NULL,
[TransferYearEndAccount_ES] [bigint] NULL,
[Type] [varchar] (256) NULL,
[TypeEnumID] [varchar] (51) NULL,
[UnitOfMeasure] [bigint] NULL,
[UserInfoId] [varchar] (20) NULL,
[ValidateCurrency] [varchar] (256) NULL,
[ValidateCurrencyEnumID] [varchar] (51) NULL,
[ValidatePosting] [varchar] (256) NULL,
[ValidatePostingEnumID] [varchar] (51) NULL,
[ValidateUser] [varchar] (256) NULL,
[ValidateUserEnumID] [varchar] (51) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MainAccount] ADD CONSTRAINT [PK_MainAccount_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[MainAccount] TO [OH_BasicReadOnly]
GO
