CREATE TABLE [dbo].[DimensionAttribute]
(
[BackingEntityKeyFieldId] [varchar] (51) NULL,
[BackingEntityKeyFieldName] [varchar] (81) NULL,
[BackingEntityTableId] [varchar] (51) NULL,
[BackingEntityTableName] [varchar] (81) NULL,
[BackingEntityType] [varchar] (51) NULL,
[BackingEntityValueFieldId] [varchar] (51) NULL,
[BackingEntityValueFieldName] [varchar] (81) NULL,
[BalancingDimension_PSN] [bigint] NULL,
[CopyValuesOnCreate] [varchar] (3) NULL,
[CopyValuesOnCreateFlag] [bit] NULL,
[CREATEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [date] NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DimensionKeyColumnName] [varchar] (81) NULL,
[DimensionValueColumnName] [varchar] (81) NULL,
[GiveDerivedDimensionsPrecedence] [varchar] (3) NULL,
[GiveDerivedDimensionsPrecedenceFlag] [bit] NULL,
[HashKey] [varchar] (50) NULL,
[IsBalancing_PSN] [varchar] (3) NULL,
[IsBalancing_PSNFlag] [bit] NULL,
[KeyAttribute] [varchar] (51) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[MODIFIEDDATETIME] [date] NULL,
[Name] [varchar] (120) NULL,
[NameAttribute] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[ReportColumnName] [varchar] (6) NULL,
[TranslationKeyFieldId] [varchar] (51) NULL,
[TranslationKeyFieldName] [varchar] (81) NULL,
[TranslationLanguageIdFieldId] [varchar] (51) NULL,
[TranslationLanguageIdFieldName] [varchar] (81) NULL,
[TranslationNameFieldId] [varchar] (51) NULL,
[TranslationNameFieldName] [varchar] (81) NULL,
[TranslationTableId] [varchar] (51) NULL,
[TranslationTableName] [varchar] (81) NULL,
[TranslationViewId] [varchar] (51) NULL,
[TranslationViewKeyFieldId] [varchar] (51) NULL,
[TranslationViewKeyFieldName] [varchar] (81) NULL,
[TranslationViewLanguageIdFieldId] [varchar] (51) NULL,
[TranslationViewLanguageIdFieldName] [varchar] (81) NULL,
[TranslationViewName] [varchar] (81) NULL,
[TranslationViewNameFieldId] [varchar] (51) NULL,
[TranslationViewNameFieldName] [varchar] (81) NULL,
[TranslationViewSystemLanguageIdFieldId] [varchar] (51) NULL,
[TranslationViewSystemLanguageIdFieldName] [varchar] (81) NULL,
[TranslationViewTranslatedNameFieldId] [varchar] (51) NULL,
[TranslationViewTranslatedNameFieldName] [varchar] (81) NULL,
[TranslationViewValueFieldId] [varchar] (51) NULL,
[TranslationViewValueFieldName] [varchar] (81) NULL,
[Type] [varchar] (256) NULL,
[TypeEnumID] [varchar] (51) NULL,
[UseTranslationNameMethod] [varchar] (3) NULL,
[UseTranslationNameMethodFlag] [bit] NULL,
[ValueAttribute] [varchar] (51) NULL,
[ViewName] [varchar] (81) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimensionAttribute] ADD CONSTRAINT [PK_DimensionAttribute_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
