CREATE TABLE [dbo].[TaxParameters]
(
[AdvancedSalesTaxPayment_IN] [varchar] (51) NULL,
[AllowDuplicates] [varchar] (51) NULL,
[BankExchRate_W] [varchar] (3) NULL,
[BankExchRate_WFlag] [bit] NULL,
[BASFormatMapping_AU] [varchar] (51) NULL,
[CalculatePrinciple] [varchar] (256) NULL,
[CalculatePrincipleEnumID] [varchar] (51) NULL,
[CashDiscOnInvoice] [varchar] (51) NULL,
[CheckIntersection] [varchar] (256) NULL,
[CheckIntersectionEnumID] [varchar] (51) NULL,
[CheckSalesTaxTransaction] [varchar] (3) NULL,
[CheckSalesTaxTransactionFlag] [bit] NULL,
[ConditionalTax] [varchar] (51) NULL,
[CustomerCalculationDateType_IN] [varchar] (256) NULL,
[CustomerCalculationDateType_INEnumID] [varchar] (51) NULL,
[Customs_IN] [varchar] (51) NULL,
[DataAreaId] [varchar] (4) NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DateForSecondTaxRaise_JP] [date] NULL,
[DeductionPercent_LT] [numeric] (18, 2) NULL,
[DefaultInvoiceType_MY] [varchar] (256) NULL,
[DefaultInvoiceType_MYEnumID] [varchar] (51) NULL,
[DelayTaxCalculation] [varchar] (3) NULL,
[DelayTaxCalculationFlag] [bit] NULL,
[DomesticTaxAggregatedERFormatMapping_IT] [varchar] (51) NULL,
[DomesticTaxAnalyticERFormatMapping_IT] [varchar] (51) NULL,
[DomesticTaxCancellationERFormatMapping_IT] [varchar] (51) NULL,
[ExchRateDiffDocType_RU] [varchar] (256) NULL,
[ExchRateDiffDocType_RUEnumID] [varchar] (51) NULL,
[Excise_IN] [varchar] (51) NULL,
[EximIncentiveSchemes_IN] [varchar] (51) NULL,
[FactureJournalFormatMappingID] [varchar] (51) NULL,
[GSTAuditFileFormatMapping_MY] [varchar] (51) NULL,
[GSTExemptPrintCode_MY] [varchar] (10) NULL,
[GSTGAFVersion_MY] [varchar] (20) NULL,
[GSTInvoiceFormat_MY] [varchar] (256) NULL,
[GSTInvoiceFormat_MYEnumID] [varchar] (51) NULL,
[GSTSummaryDelimiter_MY] [varchar] (5) NULL,
[IncludeDelimiterInGSTSummary_MY] [varchar] (51) NULL,
[IncludeTaxCodeInGSTSummary_MY] [varchar] (51) NULL,
[IncludeTaxValueInGSTSummary_MY] [varchar] (51) NULL,
[IncomingVATPayment_RU] [varchar] (3) NULL,
[IncomingVATPayment_RUFlag] [bit] NULL,
[IndirectTaxERFormatMapping_RU] [varchar] (51) NULL,
[ItemizedVATStatement_HU] [varchar] (51) NULL,
[ItemizedVATStatementLimit_HU] [numeric] (18, 2) NULL,
[JournalInclTax] [varchar] (51) NULL,
[KEY_] [int] NULL,
[MainEconomicActivityCode_CZ] [varchar] (6) NULL,
[MainEconomicActivityCode_LT] [varchar] (6) NULL,
[MandatoryTaxDirection] [varchar] (51) NULL,
[MCRAutoTaxSearch] [varchar] (51) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[MODIFIEDDATETIME] [date] NULL,
[NaturalPersonFirstName_CZ] [varchar] (20) NULL,
[NaturalPersonLastName_CZ] [varchar] (36) NULL,
[PARTITION] [bigint] NULL,
[PersonTitle_CZ] [varchar] (30) NULL,
[PSNIsCanadianHSTRules] [varchar] (51) NULL,
[PurchTaxOnOperations] [varchar] (51) NULL,
[QuarterlyVATComERFormatMapping_IT] [varchar] (51) NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[ReportAdjustment] [varchar] (3) NULL,
[ReportAdjustmentFlag] [bit] NULL,
[ReportUseVatDueDate_W] [varchar] (3) NULL,
[ReportUseVatDueDate_WFlag] [bit] NULL,
[RestoredVATCalcMethod_RU] [varchar] (256) NULL,
[RestoredVATCalcMethod_RUEnumID] [varchar] (51) NULL,
[RestoredVATGainCalcMethod_RU] [varchar] (256) NULL,
[RestoredVATGainCalcMethod_RUEnumID] [varchar] (51) NULL,
[ReverseOnCashDisc] [varchar] (51) NULL,
[ReverseSettlementDatePrinciple_W] [varchar] (3) NULL,
[ReverseSettlementDatePrinciple_WFlag] [bit] NULL,
[SAFTAccountingBooksERFormatMapping_PL] [varchar] (51) NULL,
[SAFTBankStatementERFormatMapping_PL] [varchar] (51) NULL,
[SAFTERFormatMapping_W] [varchar] (51) NULL,
[SAFTInventoryERFormatMapping_PL] [varchar] (51) NULL,
[SAFTVATInvoicesERFormatMapping_PL] [varchar] (51) NULL,
[SAFTVATSalesPurchERFormatMapping_PL] [varchar] (51) NULL,
[SalesTax_IN] [varchar] (51) NULL,
[SalesTaxPayableExchangeRateType] [varchar] (51) NULL,
[SalesTaxReceivableExchangeRateType] [varchar] (51) NULL,
[ServiceTax_IN] [varchar] (51) NULL,
[ServiceTaxACBasis_IN] [varchar] (256) NULL,
[ServiceTaxACBasis_INEnumID] [varchar] (51) NULL,
[TaxBranchEnabled] [varchar] (51) NULL,
[TaxCalculationDateType] [varchar] (256) NULL,
[TaxCalculationDateTypeEnumID] [varchar] (51) NULL,
[TaxCalculationRetryNumber] [int] NULL,
[TaxCurConvPath] [varchar] (256) NULL,
[TaxCurConvPathEnumID] [varchar] (51) NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TaxLessCashDisc] [varchar] (3) NULL,
[TaxLessCashDiscFlag] [bit] NULL,
[TaxObligationCompany] [varchar] (256) NULL,
[TaxObligationCompanyEnumID] [varchar] (51) NULL,
[TaxOnOverpayment] [varchar] (3) NULL,
[TaxOnOverpaymentFlag] [bit] NULL,
[TaxpayerStatus_CZ] [varchar] (256) NULL,
[TaxpayerStatus_CZEnumID] [varchar] (51) NULL,
[TaxpayerType_CZ] [varchar] (256) NULL,
[TaxpayerType_CZEnumID] [varchar] (51) NULL,
[TaxRecoverable_IN] [varchar] (51) NULL,
[TaxReport_JP] [varchar] (51) NULL,
[TaxReportCombineVoucherForGainLoss] [varchar] (3) NULL,
[TaxReportCombineVoucherForGainLossFlag] [bit] NULL,
[TaxReportFactor_CZ] [numeric] (18, 2) NULL,
[TaxReportFormatMappingID_UK] [varchar] (51) NULL,
[TaxSpecifyLine] [varchar] (51) NULL,
[TaxSpecPosting_RU] [varchar] (51) NULL,
[TaxYearlyComERFormatMapping_IT] [varchar] (51) NULL,
[UseCommonSAFTReport] [varchar] (51) NULL,
[UseSelfBilledInvoice_MY] [varchar] (51) NULL,
[ValidateTaxCode] [varchar] (51) NULL,
[VAT_IN] [varchar] (51) NULL,
[VendorCalculationDateType_IN] [varchar] (256) NULL,
[VendorCalculationDateType_INEnumID] [varchar] (51) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TaxParameters] ADD CONSTRAINT [PK_TaxParameters_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
