CREATE TABLE [dbo].[LedgerJournalTable]
(
[Approver] [bigint] NULL,
[AssetLeaseProcessId] [varchar] (50) NULL,
[AssetTransferType_LT] [varchar] (256) NULL,
[AssetTransferType_LTEnumID] [varchar] (51) NULL,
[BankAccountId] [varchar] (10) NULL,
[BankRemittanceType] [varchar] (256) NULL,
[BankRemittanceTypeEnumID] [varchar] (51) NULL,
[CREATEDBY] [varchar] (20) NULL,
[CurrencyCode] [varchar] (3) NULL,
[CurrentOperationsTax] [varchar] (256) NULL,
[CurrentOperationsTaxEnumID] [varchar] (51) NULL,
[CustVendNegInstProtestProcess] [varchar] (256) NULL,
[CustVendNegInstProtestProcessEnumID] [varchar] (51) NULL,
[DataAreaId] [varchar] (4) NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DefaultDimension] [varchar] (51) NULL,
[DelayTaxCalculation] [varchar] (3) NULL,
[DelayTaxCalculationFlag] [bit] NULL,
[DetailSummaryPosting] [varchar] (256) NULL,
[DetailSummaryPostingEnumID] [varchar] (51) NULL,
[DocumentNum] [varchar] (20) NULL,
[EndBalance] [numeric] (18, 2) NULL,
[EUROTriangulation] [varchar] (51) NULL,
[ExchRate] [varchar] (51) NULL,
[ExchrateSecondary] [varchar] (51) NULL,
[FixedExchRate] [varchar] (51) NULL,
[FixedOffsetAccount] [varchar] (51) NULL,
[GroupBlockId] [varchar] (10) NULL,
[IntegrationKey] [varchar] (20) NULL,
[InUseBy] [varchar] (20) NULL,
[IsAdjustmentJournal] [varchar] (3) NULL,
[IsAdjustmentJournalFlag] [bit] NULL,
[IsLedgerDimensionNameUpdated] [varchar] (3) NULL,
[IsLedgerDimensionNameUpdatedFlag] [bit] NULL,
[JournalBalance] [numeric] (18, 2) NULL,
[JournalName] [varchar] (10) NULL,
[JournalNum] [varchar] (30) NULL,
[JournalTotalCredit] [numeric] (18, 2) NULL,
[JournalTotalCreditReportingCurrency] [numeric] (18, 2) NULL,
[JournalTotalDebit] [numeric] (18, 2) NULL,
[JournalTotalDebitReportingCurrency] [numeric] (18, 2) NULL,
[journalTotalOffsetBalance] [numeric] (18, 2) NULL,
[JournalType] [varchar] (256) NULL,
[JournalTypeEnumID] [varchar] (51) NULL,
[LedgerJournalInclTax] [varchar] (51) NULL,
[LinesLimitBeforeDistribution] [varchar] (51) NULL,
[Log] [varchar] (255) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[Name] [varchar] (120) NULL,
[NumberSequenceTable] [bigint] NULL,
[NumOfLines] [varchar] (51) NULL,
[OffsetAccountType] [varchar] (256) NULL,
[OffsetAccountTypeEnumID] [varchar] (51) NULL,
[OffsetLedgerDimension] [varchar] (51) NULL,
[OriginalCompany] [varchar] (4) NULL,
[OriginalJournalNum] [varchar] (30) NULL,
[OverrideSalesTax] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[PaymentsGenerated_IT] [varchar] (3) NULL,
[PaymentsGenerated_ITFlag] [bit] NULL,
[Posted] [varchar] (51) NULL,
[PostedDateTime] [date] NULL,
[POSTEDDATETIMETZID] [int] NULL,
[ProtestSettledBill] [varchar] (51) NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[RejectedBy] [varchar] (20) NULL,
[REMOVELINEAFTERPOSTING] [int] NULL,
[ReportedAsReadyBy] [varchar] (20) NULL,
[ReportingCurrencyExchRate] [varchar] (51) NULL,
[ReportingCurrencyExchRateSecondary] [varchar] (51) NULL,
[ReportingCurrencyFixedExchRate] [varchar] (51) NULL,
[RetailStatementId] [varchar] (20) NULL,
[ReverseDate] [date] NULL,
[ReverseEntry] [varchar] (3) NULL,
[ReverseEntryFlag] [bit] NULL,
[RevRecReallocationId] [varchar] (20) NULL,
[SessionId] [varchar] (51) NULL,
[SessionLoginDateTime] [date] NULL,
[SESSIONLOGINDATETIMETZID] [int] NULL,
[SimulationPosted_IT] [varchar] (3) NULL,
[SimulationPosted_ITFlag] [bit] NULL,
[SystemBlocked] [varchar] (51) NULL,
[TaxObligationCompany] [varchar] (256) NULL,
[TaxObligationCompanyEnumID] [varchar] (51) NULL,
[UserBlockId] [varchar] (20) NULL,
[VoucherAllocatedAtPosting] [varchar] (51) NULL,
[WorkflowApprovalStatus] [varchar] (256) NULL,
[WorkflowApprovalStatusEnumID] [varchar] (51) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LedgerJournalTable] ADD CONSTRAINT [PK_LedgerJournalTable_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_dbo_NC_LedgerJournalTable_RecID] ON [dbo].[LedgerJournalTable] ([RECID]) ON [PRIMARY]
GO
