CREATE TABLE [dbo].[SAB_ConsWorkOrderLine]
(
[ChangedBy] [bigint] NULL,
[ChangeReason] [bigint] NULL,
[CostCategory] [bigint] NULL,
[CREATEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [date] NULL,
[CSRequestLine] [bigint] NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DesignCenterAttributeChanged] [varchar] (3) NULL,
[DesignCenterAttributeChangedFlag] [bit] NULL,
[DesignCenterAttributeDateTime] [date] NULL,
[DESIGNCENTERATTRIBUTEDATETIMETZID] [int] NULL,
[EntryType] [varchar] (256) NULL,
[EntryTypeEnumID] [varchar] (51) NULL,
[EquipRentalEstimatedEndDate] [date] NULL,
[EquipRentalStartDate] [date] NULL,
[FinancialInstance] [bigint] NULL,
[InventUnit] [varchar] (10) NULL,
[IsDeleted] [varchar] (51) NULL,
[IsModified] [varchar] (51) NULL,
[ItemId] [varchar] (20) NULL,
[LineAmount] [numeric] (18, 6) NULL,
[LineNumber] [bigint] NULL,
[LineType] [varchar] (256) NULL,
[LineTypeEnumID] [varchar] (51) NULL,
[Location] [bigint] NULL,
[LocationGroup] [bigint] NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[MODIFIEDDATETIME] [date] NULL,
[Name] [varchar] (1000) NULL,
[NoteChanged] [varchar] (3) NULL,
[NoteChangedFlag] [bit] NULL,
[OPTION_] [bigint] NULL,
[Orientation] [varchar] (256) NULL,
[OrientationEnumID] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[PriceOverride] [varchar] (51) NULL,
[PurchPrice] [varchar] (51) NULL,
[PurchQty] [varchar] (51) NULL,
[PurchQtyRemain] [varchar] (51) NULL,
[PurchUnit] [varchar] (10) NULL,
[QtyOrdered] [varchar] (51) NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[SupplementAmount] [numeric] (18, 2) NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TradeType] [bigint] NULL,
[Vendor] [bigint] NULL,
[WorkOrder] [bigint] NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SAB_ConsWorkOrderLine] ADD CONSTRAINT [PK_SAB_ConsWorkOrderLine_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
