CREATE TABLE [dbo].[LedgerJournalTrans]
(
[AccountAgreementId_RU] [varchar] (30) NULL,
[AccountType] [varchar] (256) NULL,
[AccountTypeEnumID] [varchar] (51) NULL,
[AcknowledgementDate] [date] NULL,
[Addressing_PL] [varchar] (250) NULL,
[AgreementCompany_RU] [varchar] (4) NULL,
[AmountCurCredit] [numeric] (18, 2) NULL,
[AmountCurDebit] [numeric] (18, 2) NULL,
[AnnouncementNum_RU] [varchar] (30) NULL,
[Approved] [varchar] (51) NULL,
[Approver] [bigint] NULL,
[AssetLeasePostingTypes] [varchar] (256) NULL,
[AssetLeasePostingTypesEnumID] [varchar] (51) NULL,
[AssetLeaseStatus] [varchar] (51) NULL,
[Attachments_CN] [int] NULL,
[BankAccountId] [varchar] (10) NULL,
[BankAgreementExt_RU] [bigint] NULL,
[BankBillOfExchangeNum] [varchar] (20) NULL,
[BankCentralBankPurposeCode] [varchar] (10) NULL,
[BankCentralBankPurposeText] [varchar] (210) NULL,
[BankCentralBankTransTypeCur_RU] [varchar] (10) NULL,
[BankChequeDepositTransRefRecID] [bigint] NULL,
[BankChequeNum] [varchar] (20) NULL,
[BankClientDocumentTypeId_RU] [varchar] (2) NULL,
[BankCommAccountId_RU] [varchar] (10) NULL,
[BankCurrency] [varchar] (3) NULL,
[BankCurrencyAmount] [numeric] (18, 2) NULL,
[BankCurrencyDealCourse_RU] [varchar] (51) NULL,
[BankCurrencyTransferLog_RU] [bigint] NULL,
[BankDepositNum] [varchar] (30) NULL,
[BankDepositVoucher] [varchar] (51) NULL,
[BankNegInstRecipientName] [varchar] (120) NULL,
[BankPaymentRegistrationNum_LV] [varchar] (20) NULL,
[BankPrintAccountNum_RU] [varchar] (20) NULL,
[BankPromissoryNoteNum] [varchar] (20) NULL,
[BankReconcileAccountAtPost] [varchar] (3) NULL,
[BankReconcileAccountAtPostFlag] [bit] NULL,
[BankRemittanceFileId] [varchar] (10) NULL,
[BankRemittanceType] [varchar] (256) NULL,
[BankRemittanceTypeEnumID] [varchar] (51) NULL,
[BankRespWorkerId_RU] [bigint] NULL,
[BankSpecAccountId_RU] [varchar] (10) NULL,
[BankTransType] [varchar] (10) NULL,
[BankVendAccountId_RU] [varchar] (20) NULL,
[BudgetSourceLedgerEntryUnposted] [bigint] NULL,
[Cancel] [varchar] (51) NULL,
[CashDiscAmount] [numeric] (18, 2) NULL,
[CashDiscBaseDate] [date] NULL,
[CashDiscBaseDays] [int] NULL,
[CashDiscCode] [varchar] (10) NULL,
[CashDiscPercent] [varchar] (51) NULL,
[CashReceiptNum_LV] [varchar] (20) NULL,
[CFDIUUID_MX] [varchar] (36) NULL,
[CommProfileType_RU] [varchar] (256) NULL,
[CommProfileType_RUEnumID] [varchar] (51) NULL,
[Company] [varchar] (4) NULL,
[Correct_RU] [varchar] (51) NULL,
[CorrectedInvoiceDate_RU] [date] NULL,
[CorrectedInvoiceId_RU] [varchar] (30) NULL,
[CorrectionType_RU] [varchar] (256) NULL,
[CorrectionType_RUEnumID] [varchar] (51) NULL,
[CreditCardAuthTransRefId] [bigint] NULL,
[CurrencyCode] [varchar] (3) NULL,
[CustBankAccount] [bigint] NULL,
[CustEinvoicePaymDeliveryNum] [int] NULL,
[CustEinvoicePaymSectionNum] [int] NULL,
[CustEinvoicePaymTransNum] [int] NULL,
[CustFactureAutoCreate_RU] [varchar] (51) NULL,
[CustTransId] [bigint] NULL,
[CustVendAccount_PL] [varchar] (10) NULL,
[CustVendBankAccountId] [varchar] (10) NULL,
[CustVendName_PL] [varchar] (100) NULL,
[CustVendNegInstProtestReason] [varchar] (256) NULL,
[CustVendNegInstProtestReasonEnumID] [varchar] (51) NULL,
[DataAreaId] [varchar] (4) NULL,
[DataLakeModified_DateTime] [datetime2] (0) NULL,
[DateCashDisc] [date] NULL,
[DebitCurrencyCode_LT] [varchar] (3) NULL,
[DefaultDimension] [varchar] (51) NULL,
[DelayTaxCalculation] [varchar] (3) NULL,
[DelayTaxCalculationFlag] [bit] NULL,
[DirectDebitMandate] [bigint] NULL,
[DocumentDate] [date] NULL,
[DocumentNum] [varchar] (20) NULL,
[Due] [date] NULL,
[ElectronicPaymentNumber] [varchar] (35) NULL,
[EnterpriseNumber] [varchar] (50) NULL,
[ErrorCodePayment] [varchar] (30) NULL,
[EUSalesList] [varchar] (30) NULL,
[ExchRate] [varchar] (51) NULL,
[ExchRateSecond] [varchar] (51) NULL,
[FBSpedEcfDerexClasificationCode_BR] [bigint] NULL,
[FileCreated] [date] NULL,
[ForeignCompany] [varchar] (4) NULL,
[ForeignVoucher] [varchar] (30) NULL,
[FreqCode] [varchar] (256) NULL,
[FreqCodeEnumID] [varchar] (51) NULL,
[FreqValue] [int] NULL,
[FurtherPostingRecId] [bigint] NULL,
[FurtherPostingType] [varchar] (51) NULL,
[GSTHSTTaxType_CA] [varchar] (256) NULL,
[GSTHSTTaxType_CAEnumID] [varchar] (51) NULL,
[ImportDate] [date] NULL,
[InformByPhone_LT] [varchar] (51) NULL,
[InformByTelex_LT] [varchar] (51) NULL,
[IntBank_LV] [varchar] (10) NULL,
[IntentLetterId_IT] [varchar] (10) NULL,
[IntraComVATDueDate_W] [varchar] (51) NULL,
[Invisible] [varchar] (3) NULL,
[InvisibleFlag] [bit] NULL,
[Invoice] [varchar] (30) NULL,
[InvoiceReleaseDate] [varchar] (51) NULL,
[INVOICERELEASEDATETZID] [int] NULL,
[InvoiceSeries_MX] [varchar] (10) NULL,
[ITMCostArea] [varchar] (256) NULL,
[ITMCostAreaEnumID] [varchar] (51) NULL,
[ITMCostRefRecId] [bigint] NULL,
[ITMCostTypeId] [varchar] (30) NULL,
[JournalNum] [varchar] (30) NULL,
[LastTransferred] [date] NULL,
[LedgerDimension] [varchar] (51) NULL,
[LedgerDimensionName] [varchar] (100) NULL,
[LedgerJournalDlvDate_ES] [date] NULL,
[LedgerVoucherType_CN] [bigint] NULL,
[LineNum] [numeric] (18, 2) NULL,
[Listcode] [varchar] (51) NULL,
[LoadingDate] [date] NULL,
[MarkedInvoice] [varchar] (30) NULL,
[MarkedInvoiceCompany] [varchar] (4) NULL,
[MarkedInvoiceRecId] [bigint] NULL,
[MarkupCode_RU] [varchar] (10) NULL,
[MCRCCGeneralLedgerId] [varchar] (30) NULL,
[MCRPaymOrderID] [varchar] (30) NULL,
[MCRPrintTxtOnCheck] [varchar] (51) NULL,
[MCRRefPaymID] [bigint] NULL,
[MODIFIEDDATETIME] [date] NULL,
[NegInstId] [varchar] (30) NULL,
[NoEdit] [varchar] (3) NULL,
[NoEditFlag] [bit] NULL,
[OffSessionId_RU] [varchar] (30) NULL,
[OffsetAccountAgreementId_RU] [varchar] (30) NULL,
[OffsetAccountType] [varchar] (256) NULL,
[OffsetAccountTypeEnumID] [varchar] (51) NULL,
[OffsetAgreementCompany_RU] [varchar] (4) NULL,
[OffsetCompany] [varchar] (4) NULL,
[OffsetDefaultDimension] [varchar] (51) NULL,
[OffsetLedgerDimension] [varchar] (51) NULL,
[OffsetPostingProfile_RU] [varchar] (10) NULL,
[OffsetTxt] [varchar] (512) NULL,
[OperationType_MX] [varchar] (256) NULL,
[OperationType_MXEnumID] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[Payment] [varchar] (100) NULL,
[PaymentAccount] [varchar] (10) NULL,
[PaymentNotes] [varchar] (1000) NULL,
[PaymentSequenceNum] [int] NULL,
[PaymentStatus] [varchar] (256) NULL,
[PaymentStatusEnumID] [varchar] (51) NULL,
[PaymId] [varchar] (200) NULL,
[PaymInstruction1] [bigint] NULL,
[PaymInstruction2] [bigint] NULL,
[PaymInstruction3] [bigint] NULL,
[PaymInstruction4] [bigint] NULL,
[PaymMode] [varchar] (10) NULL,
[PaymPurpose_LT] [varchar] (5) NULL,
[PaymReference] [varchar] (35) NULL,
[PaymSched] [varchar] (30) NULL,
[PaymSpec] [varchar] (10) NULL,
[PlafondDate_IT] [date] NULL,
[PoolRecId] [bigint] NULL,
[PostingProfile] [varchar] (10) NULL,
[Prepayment] [varchar] (3) NULL,
[PrepaymentFlag] [bit] NULL,
[Price] [numeric] (18, 2) NULL,
[ProvisionalAssessment_IN] [varchar] (51) NULL,
[PurchIdRange] [varchar] (250) NULL,
[PurchLedgerPosting] [varchar] (51) NULL,
[Qty] [varchar] (51) NULL,
[RCashDocRepresPersonId] [varchar] (20) NULL,
[RCashDocRepresType] [varchar] (256) NULL,
[RCashDocRepresTypeEnumID] [varchar] (51) NULL,
[RCashPayTransType] [varchar] (256) NULL,
[RCashPayTransTypeEnumID] [varchar] (51) NULL,
[ReasonRefRecID] [bigint] NULL,
[ReceiptDate_W] [date] NULL,
[RECID] [bigint] NOT NULL,
[RECVERSION] [int] NULL,
[RefCopyReverse_CN] [bigint] NULL,
[ReleaseDate] [date] NULL,
[ReleaseDateComment] [varchar] (60) NULL,
[RELEASEDATETZID] [int] NULL,
[RemainAmount] [numeric] (18, 2) NULL,
[RemittanceAddress] [bigint] NULL,
[RemittanceLocation] [bigint] NULL,
[RemitteeCurrency] [varchar] (3) NULL,
[ReportingCurrencyExchRate] [varchar] (51) NULL,
[ReportingCurrencyExchRateSecondary] [varchar] (51) NULL,
[RepresPersonCard_W] [varchar] (100) NULL,
[RepresPersonName_W] [varchar] (120) NULL,
[ReverseDate] [date] NULL,
[ReverseEntry] [varchar] (3) NULL,
[ReverseEntryFlag] [bit] NULL,
[RevRecDeferredLine] [bigint] NULL,
[RevRecDeferredRecognizedQty] [numeric] (18, 6) NULL,
[RevRecDeferredType] [varchar] (256) NULL,
[RevRecDeferredTypeEnumID] [varchar] (51) NULL,
[RevRecId] [bigint] NULL,
[RevRecLedgerPostingType] [varchar] (256) NULL,
[RevRecLedgerPostingTypeEnumID] [varchar] (51) NULL,
[RevRecNewValuesFromReallocation] [varchar] (51) NULL,
[RevRecSalesId] [varchar] (30) NULL,
[SalesOrderId] [varchar] (30) NULL,
[SettleVoucher] [varchar] (256) NULL,
[SettleVoucherEnumID] [varchar] (51) NULL,
[SkipBlockedForManualEntryCheck] [varchar] (3) NULL,
[SkipBlockedForManualEntryCheckFlag] [bit] NULL,
[SubBillEscalationTableRecId] [varchar] (51) NULL,
[SubBillRenewalLineRecId] [varchar] (51) NULL,
[SubBillSchedLineRecId] [varchar] (51) NULL,
[Tax1099Amount] [numeric] (18, 2) NULL,
[Tax1099Fields] [bigint] NULL,
[Tax1099RecId] [bigint] NULL,
[Tax1099State] [varchar] (10) NULL,
[Tax1099StateAmount] [numeric] (18, 2) NULL,
[TaxBase_W] [varchar] (51) NULL,
[TaxCode] [varchar] (10) NULL,
[TaxDirectionControl] [varchar] (3) NULL,
[TaxDirectionControlFlag] [bit] NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TaxPeriodPaymentCode_PL] [varchar] (10) NULL,
[TaxWithholdAlternateVendorAcct_TH] [varchar] (20) NULL,
[TaxWithholdCalculate_TH] [varchar] (51) NULL,
[TaxWithholdGroup] [varchar] (10) NULL,
[TaxWithholdItemGroupHeading_TH] [bigint] NULL,
[TransactionType] [varchar] (256) NULL,
[TransactionTypeEnumID] [varchar] (51) NULL,
[TransDate] [date] NULL,
[Transfer] [varchar] (3) NULL,
[TransferFlag] [bit] NULL,
[TransferCurrency_RU] [varchar] (3) NULL,
[Transferred] [varchar] (3) NULL,
[TransferredFlag] [bit] NULL,
[TransferredBy] [varchar] (20) NULL,
[TransferredOn] [date] NULL,
[TransferredTo] [varchar] (30) NULL,
[Triangulation] [varchar] (51) NULL,
[Txt] [varchar] (512) NULL,
[UseOriginalDocumentAsFacture_RU] [varchar] (51) NULL,
[VatDueDate_W] [date] NULL,
[VATNumJournal] [varchar] (20) NULL,
[VATOnPayment_RU] [varchar] (51) NULL,
[VATOperationCode_RU] [varchar] (10) NULL,
[VATPaymRefRecId_RU] [bigint] NULL,
[VATTaxAgentVendAccount_RU] [varchar] (20) NULL,
[VendBankAccount] [bigint] NULL,
[VendInvoiceDeclaration_IS] [bigint] NULL,
[VendorVATDate] [date] NULL,
[VendPaymFeeGroup_JP] [varchar] (20) NULL,
[VendTransId] [bigint] NULL,
[Voucher] [varchar] (30) NULL,
[Voucher_CN] [varchar] (30) NULL,
[LSN] [varchar] (60) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LedgerJournalTrans] ADD CONSTRAINT [PK_LedgerJournalTrans_RecID] PRIMARY KEY CLUSTERED ([RECID]) ON [PRIMARY]
GO
