CREATE TABLE [stage].[CustTrans]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[PostingProfileClose] [varchar] (10) NULL,
[AccountingEvent] [bigint] NULL,
[AccountNum] [varchar] (20) NULL,
[AmountCur] [float] NULL,
[AmountMST] [float] NULL,
[Approved] [varchar] (51) NULL,
[Approver] [bigint] NULL,
[BankCentralBankPurposeCode] [varchar] (10) NULL,
[BankCentralBankPurposeText] [varchar] (210) NULL,
[BankLCExportLine] [bigint] NULL,
[BankRemittanceFileId] [varchar] (10) NULL,
[BillOfExchangeID] [varchar] (30) NULL,
[BillOfExchangeSeqNum] [int] NULL,
[BillOfExchangeStatus] [varchar] (51) NULL,
[CancelledPayment] [varchar] (51) NULL,
[CashDiscCode] [varchar] (10) NULL,
[CashDiscBaseDate] [varchar] (40) NULL,
[CashPayment] [varchar] (51) NULL,
[Closed] [varchar] (40) NULL,
[CollectionLetter] [varchar] (51) NULL,
[CollectionLetterCode] [varchar] (51) NULL,
[CompanyBankAccountId] [varchar] (10) NULL,
[ControlNum] [varchar] (30) NULL,
[Correct] [varchar] (51) NULL,
[CurrencyCode] [varchar] (3) NULL,
[CustBillingClassification] [bigint] NULL,
[CustExchAdjustmentRealized] [varchar] (51) NULL,
[CustExchAdjustmentUnrealized] [varchar] (51) NULL,
[DefaultDimension] [varchar] (51) NULL,
[DeliveryMode] [varchar] (10) NULL,
[DirectDebitMandate] [bigint] NULL,
[DocumentDate] [varchar] (40) NULL,
[DocumentNum] [varchar] (20) NULL,
[DueDate] [varchar] (40) NULL,
[EUROTriangulation] [varchar] (51) NULL,
[ExchAdjustment] [varchar] (51) NULL,
[ExchAdjustmentReporting] [varchar] (51) NULL,
[ExchRate] [varchar] (51) NULL,
[ExchRateSecond] [varchar] (51) NULL,
[FixedExchRate] [varchar] (51) NULL,
[Interest] [varchar] (51) NULL,
[Invoice] [varchar] (30) NULL,
[INVOICEPROJECT] [int] NULL,
[LastExchAdj] [varchar] (40) NULL,
[LastExchAdjRate] [varchar] (51) NULL,
[LastExchAdjRateReporting] [float] NULL,
[LastExchAdjVoucher] [varchar] (30) NULL,
[LastSettleAccountNum] [varchar] (20) NULL,
[LastSettleCompany] [varchar] (4) NULL,
[LastSettleDate] [varchar] (40) NULL,
[LastSettleVoucher] [varchar] (30) NULL,
[MCRPaymOrderID] [varchar] (30) NULL,
[OffsetRecid] [bigint] NULL,
[OrderAccount] [varchar] (20) NULL,
[PaymId] [varchar] (200) NULL,
[PaymMethod] [varchar] (51) NULL,
[PaymMode] [varchar] (10) NULL,
[PaymReference] [varchar] (35) NULL,
[PaymSpec] [varchar] (10) NULL,
[PostingProfile] [varchar] (10) NULL,
[Prepayment] [varchar] (51) NULL,
[ReasonRefRecId] [bigint] NULL,
[ReportingCurrencyAmount] [float] NULL,
[ReportingCurrencyExchRate] [varchar] (51) NULL,
[ReportingCurrencyExchRateSecondary] [varchar] (51) NULL,
[ReportingCurrencyCrossRate] [float] NULL,
[ReportingExchAdjustmentRealized] [varchar] (51) NULL,
[ReportingExchAdjustmentUnrealized] [varchar] (51) NULL,
[RetailCustTrans] [varchar] (51) NULL,
[RetailStoreId] [varchar] (10) NULL,
[RetailTerminalId] [varchar] (10) NULL,
[RetailTransactionId] [varchar] (44) NULL,
[SettleAmountCur] [float] NULL,
[SettleAmountMST] [float] NULL,
[SettleAmountReporting] [float] NULL,
[Settlement] [varchar] (51) NULL,
[TaxInvoiceSalesId] [varchar] (30) NULL,
[ThirdPartyBankAccountId] [varchar] (10) NULL,
[TransDate] [varchar] (40) NULL,
[TransType] [varchar] (51) NULL,
[Txt] [varchar] (512) NULL,
[Voucher] [varchar] (30) NULL,
[PaymSchedId] [varchar] (30) NULL,
[PaymTermId] [varchar] (100) NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[MODIFIEDTRANSACTIONID] [bigint] NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[CREATEDTRANSACTIONID] [bigint] NULL,
[CredManExcludeFromCreditControl] [varchar] (51) NULL,
[InvoiceType_IT] [varchar] (51) NULL,
[CustAutomationExclude] [varchar] (51) NULL,
[CustAutomationPredunningSent] [varchar] (51) NULL,
[CustAutomationPredictionSent] [varchar] (51) NULL,
[SettleAmount_MX] [float] NULL
) ON [PRIMARY]
GO
