CREATE TABLE [stage].[TaxParameters]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[AllowDuplicates] [varchar] (51) NULL,
[BankExchRate_W] [varchar] (51) NULL,
[CalculatePrinciple] [varchar] (51) NULL,
[CashDiscOnInvoice] [varchar] (51) NULL,
[CheckIntersection] [varchar] (51) NULL,
[ConditionalTax] [varchar] (51) NULL,
[CustomerCalculationDateType_IN] [varchar] (51) NULL,
[Customs_IN] [varchar] (51) NULL,
[DeductionPercent_LT] [float] NULL,
[ExchRateDiffDocType_RU] [varchar] (51) NULL,
[Excise_IN] [varchar] (51) NULL,
[EximIncentiveSchemes_IN] [varchar] (51) NULL,
[IncomingVATPayment_RU] [varchar] (51) NULL,
[ItemizedVATStatement_HU] [varchar] (51) NULL,
[ItemizedVATStatementLimit_HU] [float] NULL,
[JournalInclTax] [varchar] (51) NULL,
[KEY_] [int] NULL,
[MainEconomicActivityCode_CZ] [varchar] (6) NULL,
[MainEconomicActivityCode_LT] [varchar] (6) NULL,
[MandatoryTaxDirection] [varchar] (51) NULL,
[MCRAutoTaxSearch] [varchar] (51) NULL,
[NaturalPersonFirstName_CZ] [varchar] (20) NULL,
[NaturalPersonLastName_CZ] [varchar] (36) NULL,
[PersonTitle_CZ] [varchar] (30) NULL,
[PurchTaxOnOperations] [varchar] (51) NULL,
[ReportAdjustment] [varchar] (51) NULL,
[ReportUseVatDueDate_W] [varchar] (51) NULL,
[RestoredVATCalcMethod_RU] [varchar] (51) NULL,
[RestoredVATGainCalcMethod_RU] [varchar] (51) NULL,
[ReverseOnCashDisc] [varchar] (51) NULL,
[ReverseSettlementDatePrinciple_W] [varchar] (51) NULL,
[SalesTax_IN] [varchar] (51) NULL,
[SalesTaxPayableExchangeRateType] [varchar] (51) NULL,
[SalesTaxReceivableExchangeRateType] [varchar] (51) NULL,
[ServiceTax_IN] [varchar] (51) NULL,
[ServiceTaxACBasis_IN] [varchar] (51) NULL,
[TaxBranchEnabled] [varchar] (51) NULL,
[TaxCalculationDateType] [varchar] (51) NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TaxLessCashDisc] [varchar] (51) NULL,
[TaxObligationCompany] [varchar] (51) NULL,
[TaxOnOverpayment] [varchar] (51) NULL,
[TaxpayerStatus_CZ] [varchar] (51) NULL,
[TaxpayerType_CZ] [varchar] (51) NULL,
[TaxRecoverable_IN] [varchar] (51) NULL,
[TaxReport_JP] [varchar] (51) NULL,
[TaxReportFactor_CZ] [float] NULL,
[TaxSpecifyLine] [varchar] (51) NULL,
[TaxSpecPosting_RU] [varchar] (51) NULL,
[ValidateTaxCode] [varchar] (51) NULL,
[VAT_IN] [varchar] (51) NULL,
[VendorCalculationDateType_IN] [varchar] (51) NULL,
[DefaultInvoiceType_MY] [varchar] (51) NULL,
[GSTExemptPrintCode_MY] [varchar] (10) NULL,
[GSTGAFVersion_MY] [varchar] (20) NULL,
[GSTInvoiceFormat_MY] [varchar] (51) NULL,
[GSTSummaryDelimiter_MY] [varchar] (5) NULL,
[IncludeDelimiterInGSTSummary_MY] [varchar] (51) NULL,
[IncludeTaxCodeInGSTSummary_MY] [varchar] (51) NULL,
[IncludeTaxValueInGSTSummary_MY] [varchar] (51) NULL,
[UseSelfBilledInvoice_MY] [varchar] (51) NULL,
[BASFormatMapping_AU] [varchar] (51) NULL,
[GSTAuditFileFormatMapping_MY] [varchar] (51) NULL,
[DateForSecondTaxRaise_JP] [varchar] (40) NULL,
[DomesticTaxCancellationERFormatMapping_IT] [varchar] (51) NULL,
[DomesticTaxAggregatedERFormatMapping_IT] [varchar] (51) NULL,
[DomesticTaxAnalyticERFormatMapping_IT] [varchar] (51) NULL,
[TaxYearlyComERFormatMapping_IT] [varchar] (51) NULL,
[QuarterlyVATComERFormatMapping_IT] [varchar] (51) NULL,
[SAFTAccountingBooksERFormatMapping_PL] [varchar] (51) NULL,
[SAFTBankStatementERFormatMapping_PL] [varchar] (51) NULL,
[SAFTInventoryERFormatMapping_PL] [varchar] (51) NULL,
[SAFTVATSalesPurchERFormatMapping_PL] [varchar] (51) NULL,
[SAFTVATInvoicesERFormatMapping_PL] [varchar] (51) NULL,
[AdvancedSalesTaxPayment_IN] [varchar] (51) NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[FactureJournalFormatMappingID] [varchar] (51) NULL,
[TaxReportFormatMappingID_UK] [varchar] (51) NULL,
[IndirectTaxERFormatMapping_RU] [varchar] (51) NULL,
[SAFTERFormatMapping_W] [varchar] (51) NULL,
[DelayTaxCalculation] [varchar] (51) NULL,
[TaxCurConvPath] [varchar] (51) NULL,
[PSNIsCanadianHSTRules] [varchar] (51) NULL,
[TaxCalculationRetryNumber] [int] NULL,
[CheckSalesTaxTransaction] [varchar] (51) NULL,
[TaxReportCombineVoucherForGainLoss] [varchar] (51) NULL,
[UseCommonSAFTReport] [varchar] (51) NULL
) ON [PRIMARY]
GO
