CREATE TABLE [stage].[SAB_ConsSalesDesign]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[BuildingTypeId] [varchar] (20) NULL,
[ColorScheme] [bigint] NULL,
[FacadeId] [varchar] (20) NULL,
[Inactive] [varchar] (51) NULL,
[Lot] [bigint] NULL,
[LotStructureElement] [bigint] NULL,
[Name] [varchar] (120) NULL,
[Opportunity] [bigint] NULL,
[Orientation] [varchar] (51) NULL,
[OwnerWorker] [bigint] NULL,
[PlanChange] [varchar] (51) NULL,
[Type] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[EstimateType] [bigint] NULL,
[SalesQuickQuotation] [bigint] NULL
) ON [PRIMARY]
GO
