CREATE TABLE [stage].[SAB_ConsSalesOpportunityHistory]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[AppointmentDuration] [varchar] (51) NULL,
[AppointmentType] [bigint] NULL,
[LineNumber] [bigint] NULL,
[LotStructureElement] [bigint] NULL,
[OpportunityParty] [bigint] NULL,
[SalesRepresentativeWorker] [bigint] NULL,
[ScheduleStatus] [varchar] (51) NULL,
[TransDateTime] [varchar] (40) NULL,
[TRANSDATETIMETZID] [int] NULL,
[Type] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[Purpose] [bigint] NULL,
[Source] [bigint] NULL,
[Rating] [bigint] NULL,
[Origin] [varchar] (51) NULL
) ON [PRIMARY]
GO
