CREATE TABLE [stage].[SAB_ConsCSRequestVendorScheduleAppointment]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[FromDateTime] [varchar] (40) NULL,
[FROMDATETIMETZID] [int] NULL,
[LineNumber] [bigint] NULL,
[PendingStatusReason] [bigint] NULL,
[RequestVendorSchedule] [bigint] NULL,
[ScheduleContact] [varchar] (120) NULL,
[Status] [varchar] (51) NULL,
[ToDateTime] [varchar] (40) NULL,
[TODATETIMETZID] [int] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[CompleteDateTime] [varchar] (40) NULL,
[COMPLETEDATETIMETZID] [int] NULL
) ON [PRIMARY]
GO
