CREATE TABLE [stage].[SAB_ConsVendInvoiceTable]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[ApprovalStatus] [varchar] (51) NULL,
[Backcharge] [varchar] (51) NULL,
[DocumentDate] [varchar] (40) NULL,
[InclTax] [varchar] (51) NULL,
[InvoiceAmount] [float] NULL,
[InvoiceId] [varchar] (30) NULL,
[PaymTermId] [varchar] (100) NULL,
[Posted] [varchar] (51) NULL,
[Tax1099Amount] [float] NULL,
[Tax1099Fields] [bigint] NULL,
[Tax1099State] [varchar] (10) NULL,
[Tax1099StateAmount] [float] NULL,
[TransDate] [varchar] (40) NULL,
[TransTxt] [varchar] (120) NULL,
[VendAccount] [varchar] (20) NULL,
[Voucher] [varchar] (30) NULL,
[UtilityInvoiceEntryHold] [varchar] (51) NULL,
[UtilityInvoiceEntryOverrideReason] [bigint] NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[CREATEDBY] [varchar] (20) NULL,
[PostingProfile] [varchar] (10) NULL,
[OH_AIInvoice] [varchar] (51) NULL
) ON [PRIMARY]
GO
