CREATE TABLE [stage].[LogisticsPostalAddress]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[Address] [varchar] (250) NULL,
[Apartment_RU] [varchar] (10) NULL,
[Building_RU] [varchar] (10) NULL,
[BuildingCompliment] [varchar] (60) NULL,
[City] [varchar] (60) NULL,
[CityRecId] [bigint] NULL,
[CountryRegionId] [varchar] (10) NULL,
[County] [varchar] (30) NULL,
[District] [bigint] NULL,
[DistrictName] [varchar] (60) NULL,
[FlatId_RU] [bigint] NULL,
[HouseId_RU] [bigint] NULL,
[IsPrivate] [varchar] (51) NULL,
[Latitude] [varchar] (51) NULL,
[Location] [bigint] NULL,
[Longitude] [varchar] (51) NULL,
[PostBox] [varchar] (20) NULL,
[PrivateForParty] [bigint] NULL,
[State] [varchar] (10) NULL,
[Street] [varchar] (250) NULL,
[StreetId_RU] [bigint] NULL,
[StreetNumber] [varchar] (20) NULL,
[TimeZone] [varchar] (51) NULL,
[ValidFrom] [varchar] (40) NULL,
[VALIDFROMTZID] [int] NULL,
[ValidTo] [varchar] (40) NULL,
[VALIDTOTZID] [int] NULL,
[ZipCode] [varchar] (10) NULL,
[ZipCodeRecId] [bigint] NULL,
[CityKana_JP] [varchar] (60) NULL,
[StreetKana_JP] [varchar] (250) NULL,
[SteadId_RU] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[IsSimplifiedAddress_RU] [varchar] (51) NULL,
[ChannelReferenceId] [varchar] (38) NULL,
[SettlementRecId] [bigint] NULL,
[LocalityRecId] [bigint] NULL
) ON [PRIMARY]
GO
