CREATE TABLE [stage].[VendBankAccount]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[AccountID] [varchar] (10) NULL,
[AccountNum] [varchar] (48) NULL,
[ActiveDate] [varchar] (51) NULL,
[ACTIVEDATETZID] [int] NULL,
[BankAccountNameKana_JP] [varchar] (40) NULL,
[BankAccountType] [varchar] (51) NULL,
[BankCIN] [varchar] (1) NULL,
[BankCodeType] [varchar] (51) NULL,
[BankConstantSymbol] [bigint] NULL,
[BankContractAccount] [varchar] (11) NULL,
[BankGroupID] [varchar] (10) NULL,
[BankIBAN] [varchar] (48) NULL,
[CellularPhone] [varchar] (20) NULL,
[ContactPerson] [varchar] (120) NULL,
[CorrAccount_W] [varchar] (48) NULL,
[CorrespBank_EE] [varchar] (10) NULL,
[CurrencyCode] [varchar] (3) NULL,
[DirDunsNumber] [bigint] NULL,
[Email] [varchar] (80) NULL,
[ExchRate] [varchar] (51) NULL,
[ExchRateRef] [varchar] (11) NULL,
[ExpiryDate] [varchar] (51) NULL,
[EXPIRYDATETZID] [int] NULL,
[ForeignAccount_RU] [varchar] (48) NULL,
[ForeignBank_RU] [varchar] (10) NULL,
[ForeignSWIFT_RU] [varchar] (20) NULL,
[IntermAccount_EE] [varchar] (48) NULL,
[IntermBank_EE] [varchar] (10) NULL,
[IntermBankAccountId] [varchar] (10) NULL,
[Location] [bigint] NULL,
[LogisticsLocation] [bigint] NULL,
[LvDefaultBank] [varchar] (51) NULL,
[MsgToBank] [varchar] (255) NULL,
[Name] [varchar] (120) NULL,
[Pager] [varchar] (20) NULL,
[Phone] [varchar] (20) NULL,
[PhoneLocal] [varchar] (10) NULL,
[RegistrationNum] [varchar] (12) NULL,
[SMS] [varchar] (80) NULL,
[SpecificSymbol] [varchar] (30) NULL,
[SWIFTNo] [varchar] (20) NULL,
[TeleFax] [varchar] (20) NULL,
[Telex] [varchar] (20) NULL,
[TransType_JP] [varchar] (51) NULL,
[URL] [varchar] (255) NULL,
[VendAccount] [varchar] (20) NULL,
[VendDuns4Number] [varchar] (4) NULL,
[VendPaymentTextCode] [varchar] (10) NULL,
[FICreditorID_DK] [varchar] (8) NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[QRIBAN_CH] [varchar] (48) NULL,
[SpecParameters_CH] [varchar] (40) NULL,
[Comments] [varchar] (120) NULL,
[Reviewed] [varchar] (51) NULL,
[BankInformationOrigin] [varchar] (51) NULL
) ON [PRIMARY]
GO
