CREATE TABLE [stage].[SysUserInfo]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[compilerTarget] [varchar] (51) NULL,
[DefaultCountryRegion] [varchar] (10) NULL,
[docuHandlingActive] [varchar] (51) NULL,
[DOCUTOOLBARBUTTONACTIVE] [int] NULL,
[Email] [varchar] (80) NULL,
[EventEmailAlertsWhen] [varchar] (51) NULL,
[EventPollFrequency] [int] NULL,
[EventPopUpDisplayWhen] [varchar] (51) NULL,
[EventPopUpLinkDestination] [varchar] (51) NULL,
[EventPopUps] [varchar] (51) NULL,
[EventWorkflowShowPopup] [varchar] (51) NULL,
[EventWorkflowTasksInClient] [varchar] (51) NULL,
[EventWorkflowTasksInEmail] [varchar] (51) NULL,
[HelpMarkEmptyLinks] [varchar] (51) NULL,
[HelpTheme] [varchar] (120) NULL,
[Id] [varchar] (20) NULL,
[Language] [varchar] (7) NULL,
[SqmEnabled] [varchar] (51) NULL,
[SqmUserGuid] [varchar] (50) NULL,
[WorkflowLineItemNotificationFormat] [varchar] (51) NULL,
[Density] [varchar] (51) NULL,
[Theme] [varchar] (51) NULL,
[StartPage] [varchar] (60) NULL,
[defaultExcelExportSite] [varchar] (255) NULL,
[defaultExcelExportPath] [varchar] (255) NULL,
[Mailer] [varchar] (10) NULL,
[AutomaticUrlUpdate] [varchar] (51) NULL,
[EnhancedTabSequence] [varchar] (51) NULL,
[NegativeAmountsInRed_CN] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[EventWorkflowTasksInActionCenter] [varchar] (51) NULL,
[TooltipOnFocus] [varchar] (51) NULL,
[EventWorkflowAlternateEmail] [varchar] (80) NULL,
[OH_SandboxUser] [varchar] (51) NULL,
[OH_DevUser] [varchar] (51) NULL,
[ShowTaskListOnDefaultDashboard] [varchar] (51) NULL
) ON [PRIMARY]
GO
