CREATE TABLE [stage].[SAB_ConsWorkOrderLineHistory]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[ChangedBy] [bigint] NULL,
[ChangeReason] [bigint] NULL,
[CostCategory] [bigint] NULL,
[CSRequestLine] [bigint] NULL,
[DesignCenterAttributeChanged] [varchar] (51) NULL,
[EntryType] [varchar] (51) NULL,
[FinancialInstance] [bigint] NULL,
[InventUnit] [varchar] (10) NULL,
[ItemId] [varchar] (20) NULL,
[LineAmount] [varchar] (51) NULL,
[LineNumber] [bigint] NULL,
[LineType] [varchar] (51) NULL,
[Location] [bigint] NULL,
[LocationGroup] [bigint] NULL,
[Name] [varchar] (1000) NULL,
[NoteChanged] [varchar] (51) NULL,
[OPTION_] [bigint] NULL,
[Orientation] [varchar] (51) NULL,
[PurchPrice] [varchar] (51) NULL,
[PurchQty] [varchar] (51) NULL,
[PurchUnit] [varchar] (10) NULL,
[QtyOrdered] [varchar] (51) NULL,
[SupplementAmount] [float] NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TaxGroup] [varchar] (10) NULL,
[ValidFrom] [varchar] (40) NULL,
[VALIDFROMTZID] [int] NULL,
[ValidTo] [varchar] (40) NULL,
[VALIDTOTZID] [int] NULL,
[WorkOrder] [bigint] NULL,
[WorkOrderLine] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[DesignCenterAttributeDateTime] [varchar] (40) NULL,
[DESIGNCENTERATTRIBUTEDATETIMETZID] [int] NULL,
[Vendor] [bigint] NULL,
[EquipRentalEstimatedEndDate] [varchar] (40) NULL,
[EquipRentalStartDate] [varchar] (40) NULL,
[TradeType] [bigint] NULL
) ON [PRIMARY]
GO
