CREATE TABLE [stage].[SAB_ConsSalesDepositTrans]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[Amount] [float] NULL,
[Correction] [varchar] (51) NULL,
[DeductedAmount] [float] NULL,
[DepositReasonId] [varchar] (10) NULL,
[PaymentDate] [varchar] (40) NULL,
[PaymMode] [varchar] (10) NULL,
[PaymReference] [varchar] (35) NULL,
[PostingProfile] [varchar] (10) NULL,
[SalesDesign] [bigint] NULL,
[TransDate] [varchar] (40) NULL,
[Type] [varchar] (51) NULL,
[Voucher] [varchar] (30) NULL,
[DepositRefund] [bigint] NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[AlternateRemitToPerson] [bigint] NULL,
[LineNumber] [bigint] NULL,
[Opportunity] [bigint] NULL,
[SaleOrigin] [bigint] NULL
) ON [PRIMARY]
GO
