CREATE TABLE [stage].[SAB_ConsSalesQuotationTrans]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[ChangeType] [varchar] (51) NULL,
[CostPrice] [float] NULL,
[Description] [varchar] (120) NULL,
[DiscountAmount] [float] NULL,
[DiscountType] [bigint] NULL,
[DocumentSection] [bigint] NULL,
[FreeTxt] [varchar] (1000) NULL,
[ItemId] [varchar] (20) NULL,
[LineAmount] [varchar] (51) NULL,
[LineNumber] [bigint] NULL,
[Location] [bigint] NULL,
[LocationGroup] [bigint] NULL,
[MeasuredOptionChild] [varchar] (51) NULL,
[OPTION_] [bigint] NULL,
[OptionAddSalesPriceToBase] [varchar] (51) NULL,
[OptionIncludedOption] [varchar] (51) NULL,
[OptionMaster] [bigint] NULL,
[QuotationJour] [bigint] NULL,
[RevenueCategory] [bigint] NULL,
[SalesPrice] [varchar] (51) NULL,
[SalesPriceOverriden] [varchar] (51) NULL,
[SalesQty] [varchar] (51) NULL,
[Type] [varchar] (51) NULL,
[ZeroPriceIndicator] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[Measurement] [float] NULL,
[MeasurementUnadjusted] [float] NULL,
[ReviewStatus] [varchar] (51) NULL,
[SalesPriceLocked] [varchar] (51) NULL,
[OptionMandatory] [varchar] (51) NULL,
[SalesPriceLockedUntil] [varchar] (40) NULL,
[BaseSalesPriceComponent] [varchar] (51) NULL
) ON [PRIMARY]
GO
