CREATE TABLE [stage].[SAB_ConsFinancialInstance]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[Active] [varchar] (51) NULL,
[AllocationExclude] [varchar] (51) NULL,
[BillingTemplate] [bigint] NULL,
[DataArea] [varchar] (4) NULL,
[FinancialInstanceId] [varchar] (30) NULL,
[InstanceRelationType] [bigint] NULL,
[Name] [varchar] (254) NULL,
[PostingGroup] [bigint] NULL,
[TaxGroup] [varchar] (10) NULL,
[LOT] [bigint] NULL,
[DEFAULTDIMENSION] [bigint] NULL,
[DEFAULTDIMENSIONSELLING] [bigint] NULL,
[LOTSTRUCTUREELEMENT] [bigint] NULL,
[TAXENTITY] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[RELATIONTYPE] [bigint] NULL,
[BudgetDatesLocked] [varchar] (51) NULL,
[Description] [varchar] (120) NULL,
[ReleaseGroup] [bigint] NULL,
[ACCRUED] [int] NULL,
[CLOSED] [int] NULL,
[FINALIZATIONSTATUS] [int] NULL,
[FINALIZED] [int] NULL
) ON [PRIMARY]
GO
