CREATE TABLE [stage].[GeneralJournalEntry]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[AccountingDate] [varchar] (40) NULL,
[AcknowledgementDate] [varchar] (40) NULL,
[DocumentDate] [varchar] (40) NULL,
[DocumentNumber] [varchar] (20) NULL,
[FiscalCalendarPeriod] [varchar] (51) NULL,
[FiscalCalendarYear] [varchar] (51) NULL,
[JournalCategory] [varchar] (51) NULL,
[JournalNumber] [varchar] (30) NULL,
[Ledger] [bigint] NULL,
[PostingLayer] [varchar] (51) NULL,
[TransferId] [bigint] NULL,
[SubledgerVoucher] [varchar] (30) NULL,
[SubledgerVoucherDataAreaId] [varchar] (4) NULL,
[LedgerEntryJournal] [bigint] NULL,
[LedgerPostingJournal] [varchar] (30) NULL,
[LedgerPostingJournalDataAreaId] [varchar] (4) NULL,
[BudgetSourceLedgerEntryPosted] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[CREATEDTRANSACTIONID] [bigint] NULL
) ON [PRIMARY]
GO
