CREATE TABLE [stage].[GeneralJournalAccountEntry]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[AccountingCurrencyAmount] [float] NULL,
[AllocationLevel] [varchar] (51) NULL,
[GeneralJournalEntry] [bigint] NULL,
[HistoricalExchangeRateDate] [varchar] (40) NULL,
[IsCorrection] [varchar] (51) NULL,
[IsCredit] [varchar] (51) NULL,
[LedgerAccount] [varchar] (500) NULL,
[LedgerDimension] [varchar] (51) NULL,
[PostingType] [varchar] (51) NULL,
[Quantity] [varchar] (51) NULL,
[ReportingCurrencyAmount] [float] NULL,
[Text] [varchar] (512) NULL,
[TransactionCurrencyAmount] [float] NULL,
[TransactionCurrencyCode] [varchar] (3) NULL,
[MainAccount] [bigint] NULL,
[ProjId_SA] [varchar] (20) NULL,
[ProjTableDataAreaId] [varchar] (4) NULL,
[ReasonRef] [bigint] NULL,
[PaymentReference] [varchar] (35) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CREATEDTRANSACTIONID] [bigint] NULL,
[AssetLeasePostingTypes] [varchar] (51) NULL,
[ASSETLEASETRANSACTIONTYPE] [int] NULL,
[OriginalAccountEntry] [bigint] NULL
) ON [PRIMARY]
GO
