CREATE TABLE [stage].[ContactPerson]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[AssistantName] [varchar] (120) NULL,
[AssistantPhone] [varchar] (20) NULL,
[ComputerNetworkName] [varchar] (10) NULL,
[ContactForParty] [bigint] NULL,
[ContactPersonId] [varchar] (20) NULL,
[ContactPersonParentId] [varchar] (20) NULL,
[Department] [varchar] (50) NULL,
[DirectMail] [varchar] (51) NULL,
[GovernmentIDNumber] [varchar] (50) NULL,
[Imported] [varchar] (51) NULL,
[Inactive] [varchar] (51) NULL,
[LastEditAxDateTime] [varchar] (40) NULL,
[LASTEDITAXDATETIMETZID] [int] NULL,
[Mileage] [varchar] (199) NULL,
[OfficeLocation] [varchar] (30) NULL,
[OrganizationalIDNumber] [varchar] (25) NULL,
[Party] [bigint] NULL,
[Profession] [varchar] (30) NULL,
[Sensitivity] [varchar] (51) NULL,
[Spouse] [varchar] (120) NULL,
[Title] [varchar] (30) NULL,
[WebRequestAccess] [varchar] (51) NULL,
[DocuGreeting2] [varchar] (255) NULL,
[DocuIntro2] [varchar] (25) NULL,
[BillingInformation] [varchar] (150) NULL,
[Character] [varchar] (20) NULL,
[CustAccount] [varchar] (20) NULL,
[Decision] [varchar] (20) NULL,
[DocuGreeting1] [varchar] (255) NULL,
[DocuIntro1] [varchar] (25) NULL,
[Loyalty] [varchar] (20) NULL,
[MainResponsibleWorker] [bigint] NULL,
[MCRIsDefaultContact] [varchar] (51) NULL,
[OutlookCategories] [varchar] (255) NULL,
[PayeeDocument_RU] [varchar] (100) NULL,
[TimeAvailableFrom] [varchar] (51) NULL,
[TimeAvailableTo] [varchar] (51) NULL,
[VendRole] [varchar] (51) NULL,
[VIP] [varchar] (51) NULL,
[FUNCTION_] [varchar] (251) NULL,
[VendorPortalAccessAllowed] [varchar] (51) NULL,
[IsContactPersonExternallyMaintained] [varchar] (51) NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL
) ON [PRIMARY]
GO
