CREATE TABLE [stage].[SAB_ConsInventTable]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[BidGroupByElementType] [bigint] NULL,
[CostCategory] [bigint] NULL,
[Depth] [varchar] (51) NULL,
[Description] [varchar] (1000) NULL,
[Dimensional] [varchar] (51) NULL,
[DocumentSection] [bigint] NULL,
[Height] [varchar] (51) NULL,
[InventUnitId] [varchar] (10) NULL,
[ItemId] [varchar] (20) NULL,
[Manufacturer] [bigint] NULL,
[Name] [varchar] (120) NULL,
[PurchUnitId] [varchar] (10) NULL,
[RequireLotStartOverride] [varchar] (51) NULL,
[SummaryQty] [varchar] (51) NULL,
[SummaryUnitId] [varchar] (10) NULL,
[SummaryWorkOrder] [varchar] (51) NULL,
[TaxItemGroup] [varchar] (10) NULL,
[Width] [varchar] (51) NULL,
[Inactive] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[UseNetMeasurement] [varchar] (51) NULL,
[EquipRentalGroupItemId] [varchar] (20) NULL,
[Type] [varchar] (51) NULL
) ON [PRIMARY]
GO
