CREATE TABLE [stage].[SAB_ConsLotOptionDetailsHistory]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[DiscountAmount] [float] NULL,
[DiscountType] [bigint] NULL,
[DynamicBOMDate] [varchar] (40) NULL,
[FinancialInstance] [bigint] NULL,
[ItemId] [varchar] (20) NULL,
[LineAmount] [float] NULL,
[Location] [bigint] NULL,
[LocationGroup] [bigint] NULL,
[LotStart] [bigint] NULL,
[MeasuredOptionChild] [varchar] (51) NULL,
[Measurement] [float] NULL,
[OPTION_] [bigint] NULL,
[OptionAddSalesPriceToBase] [varchar] (51) NULL,
[OptionIncludedOption] [varchar] (51) NULL,
[OptionMaster] [bigint] NULL,
[SalesOpportunity] [bigint] NULL,
[SalesPrice] [varchar] (51) NULL,
[SalesQty] [varchar] (51) NULL,
[Source] [varchar] (51) NULL,
[Type] [varchar] (51) NULL,
[ZeroPriceIndicator] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[MeasurementUnadjusted] [float] NULL,
[OptionMandatory] [varchar] (51) NULL
) ON [PRIMARY]
GO
