CREATE TABLE [stage].[SAB_ConsWBSActivities]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[ActivityNumber] [varchar] (50) NULL,
[ActualEndDate] [varchar] (40) NULL,
[BudgetEndDate] [varchar] (40) NULL,
[BudgetStartDate] [varchar] (40) NULL,
[Closed] [varchar] (51) NULL,
[ConstructionPhase] [bigint] NULL,
[DoneByWorker] [bigint] NULL,
[Duration] [varchar] (51) NULL,
[FinancialInstance] [bigint] NULL,
[LatestStartDate] [varchar] (40) NULL,
[LockState] [varchar] (51) NULL,
[Milestone] [varchar] (51) NULL,
[ReleaseGroup] [bigint] NULL,
[ReportingActivity] [bigint] NULL,
[Responsibility] [bigint] NULL,
[SchedEndDate] [varchar] (40) NULL,
[SchedStartDate] [varchar] (40) NULL,
[SchedStartDateOrig] [varchar] (40) NULL,
[Type] [varchar] (51) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[ConstructionPause] [varchar] (51) NULL,
[DurationOrig] [varchar] (51) NULL
) ON [PRIMARY]
GO
