CREATE TABLE [stage].[SAB_ConsOptionCategory]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[IsActive] [varchar] (51) NULL,
[IsOptionAttributesInherited] [varchar] (51) NULL,
[LEVEL_] [bigint] NULL,
[LocationPrompt] [varchar] (51) NULL,
[MeasuredOptions] [varchar] (51) NULL,
[Name] [varchar] (254) NULL,
[NestedSetLeft] [bigint] NULL,
[NestedSetRight] [bigint] NULL,
[ParentOptionCategory] [bigint] NULL,
[ShowMaterialPrice] [varchar] (51) NULL,
[UnitId] [varchar] (10) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MODIFIEDDATETIME] [varchar] (40) NULL,
[MODIFIEDBY] [varchar] (20) NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[DraftingRequired] [varchar] (51) NULL,
[AdminOption] [varchar] (51) NULL,
[OH_OptionSalesPriceReductionTolerance] [float] NULL,
[OH_PricingUpdateRule] [varchar] (51) NULL,
[OH_PricingAmountPercent] [float] NULL,
[OH_PricingSmartRoundingGroup] [bigint] NULL
) ON [PRIMARY]
GO
