CREATE TABLE [stage].[BankAccountTable]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[NsfLedgerJournalName] [varchar] (10) NULL,
[AccountID] [varchar] (10) NULL,
[AccountNameKana_JP] [varchar] (40) NULL,
[AccountNum] [varchar] (48) NULL,
[ActiveFrom] [varchar] (40) NULL,
[ACTIVEFROMTZID] [int] NULL,
[ActiveTo] [varchar] (40) NULL,
[ACTIVETOTZID] [int] NULL,
[BankAccountStatus] [varchar] (51) NULL,
[BankCIN] [varchar] (1) NULL,
[BankClearingCode] [varchar] (10) NULL,
[BankCodeType] [varchar] (51) NULL,
[BankCompanyStatementName] [varchar] (16) NULL,
[BankConstantSymbol] [bigint] NULL,
[BankContractAccount] [varchar] (11) NULL,
[BankDestinationName] [varchar] (23) NULL,
[BankGroupId] [varchar] (10) NULL,
[BankInterbankClearingCode_BE] [varchar] (51) NULL,
[BankMultiCurrency] [varchar] (51) NULL,
[BankPositivePayFormatName] [varchar] (10) NULL,
[BankPositivePayStartDate] [varchar] (40) NULL,
[BankReconAllowedPennyDifference] [float] NULL,
[BankReconciliationEnabled] [varchar] (51) NULL,
[BankReconciliationMatchRuleSet] [bigint] NULL,
[BankReconciliationStmtAsPaymConfirm] [varchar] (51) NULL,
[BankReconMatchAutoAfterImport] [varchar] (51) NULL,
[BankSortCode] [varchar] (10) NULL,
[BankStatementFormat] [bigint] NULL,
[BankStatementName] [varchar] (120) NULL,
[BankSuffix] [varchar] (3) NULL,
[BankTransferCode] [varchar] (15) NULL,
[CellularPhone] [varchar] (20) NULL,
[CompanyPaymId] [varchar] (35) NULL,
[ContactPerson] [varchar] (120) NULL,
[CorrAccount_W] [varchar] (48) NULL,
[CurrencyCode] [varchar] (3) NULL,
[CurrencyOrder_TemplateName_RU] [varchar] (259) NULL,
[CurrencySellOrder_TemplateName_RU] [varchar] (259) NULL,
[CustomerPaymentFeeLedgerDimension] [varchar] (51) NULL,
[CustPaymFeePost] [varchar] (51) NULL,
[DebitDirectId] [varchar] (35) NULL,
[DefaultDimension] [varchar] (51) NULL,
[DiscCreditMaxMST] [varchar] (51) NULL,
[DivisionPaymId] [varchar] (35) NULL,
[Email] [varchar] (80) NULL,
[FeeContractAccount] [varchar] (48) NULL,
[GiroContract] [varchar] (10) NULL,
[GiroContractAccount] [varchar] (11) NULL,
[IBAN] [varchar] (48) NULL,
[IncludeBankBarCode_FI] [varchar] (51) NULL,
[InvoiceRemitAmount] [float] NULL,
[InvoiceRemittanceLedgerDimension] [varchar] (51) NULL,
[isBankPrenote] [varchar] (51) NULL,
[LedgerDimension] [varchar] (51) NULL,
[LedgerJournalNameId] [varchar] (10) NULL,
[Location] [bigint] NULL,
[LvDefaultBank] [varchar] (51) NULL,
[LvPayOrderType] [varchar] (51) NULL,
[Name] [varchar] (120) NULL,
[NsfFeeMarkupGroupId] [varchar] (10) NULL,
[NsfFeeMarkupGroupModule] [varchar] (51) NULL,
[OverDraftLimit] [float] NULL,
[Pager] [varchar] (20) NULL,
[PaymForeignExportPath_LT] [varchar] (259) NULL,
[PaymLocalExportPath_LT] [varchar] (259) NULL,
[PaymOrderNumSeqId_W] [varchar] (10) NULL,
[Phone] [varchar] (20) NULL,
[PhoneLocal] [varchar] (10) NULL,
[PrenoteResponseDays] [varchar] (51) NULL,
[PrintGiro_FI] [varchar] (51) NULL,
[RegistrationNum] [varchar] (12) NULL,
[RemitCollectionAmount] [float] NULL,
[RemitDiscountAmount] [float] NULL,
[RemittanceCollectionLedgerDimension] [varchar] (51) NULL,
[RemittanceDiscountLedgerDimension] [varchar] (51) NULL,
[Rfc_MX] [varchar] (13) NULL,
[SMS] [varchar] (80) NULL,
[SpecificSymbol] [varchar] (30) NULL,
[SWIFTNo] [varchar] (20) NULL,
[TeleFax] [varchar] (20) NULL,
[Telex] [varchar] (20) NULL,
[TemplateFileName_RU] [varchar] (259) NULL,
[TransType_JP] [varchar] (51) NULL,
[URL] [varchar] (255) NULL,
[IsNACHAFileBlocked] [varchar] (51) NULL,
[TemplateRefRecId_RU] [bigint] NULL,
[CurrencyOrder_TemplateRefRecId_RU] [bigint] NULL,
[CurrencySellOrder_TemplateRefRecId_RU] [bigint] NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CFMBankBalanceMinimum] [varchar] (51) NULL,
[SAB_ConsCashFlowBankLiquidityType] [bigint] NULL,
[SAB_ConsCashFlowBankType] [bigint] NULL,
[QRIBAN_CH] [varchar] (48) NULL,
[PostingProfileBillsRemitCollection_IT] [varchar] (10) NULL,
[PostingProfileBillsRemitDiscount_IT] [varchar] (10) NULL,
[PostingProfileRemitNotes_IT] [varchar] (10) NULL,
[OH_ACHPrenoteBalancedRequired] [varchar] (51) NULL,
[IFSC_IN] [varchar] (11) NULL,
[UPIId_IN] [varchar] (50) NULL,
[UPIIName_IN] [varchar] (50) NULL,
[TimeZonePreference] [varchar] (51) NULL,
[TimeZone] [varchar] (51) NULL,
[ReverseDebitCredit] [varchar] (51) NULL
) ON [PRIMARY]
GO
