CREATE TABLE [stage].[SAB_ConsLotStructureElement]
(
[Instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[BuildingTypeId] [varchar] (20) NULL,
[CalendarId] [varchar] (10) NULL,
[ColorScheme] [bigint] NULL,
[CSExternallyManaged] [varchar] (51) NULL,
[CSExternalVendor] [bigint] NULL,
[DevelopmentId] [varchar] (10) NULL,
[DevelopmentType] [varchar] (51) NULL,
[ElementType] [bigint] NULL,
[FacadeId] [varchar] (20) NULL,
[InheritTeams] [varchar] (51) NULL,
[IsActive] [varchar] (51) NULL,
[IsLotAttributesInherited] [varchar] (51) NULL,
[LEVEL_] [bigint] NULL,
[Name] [varchar] (254) NULL,
[NestedSetLeft] [bigint] NULL,
[NestedSetRight] [bigint] NULL,
[Orientation] [varchar] (51) NULL,
[ParentLotStructureElement] [bigint] NULL,
[Party] [bigint] NULL,
[Subfloor] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[CREATEDDATETIME] [varchar] (40) NULL,
[CREATEDBY] [varchar] (20) NULL,
[TarionDateTemplate] [bigint] NULL
) ON [PRIMARY]
GO
