CREATE TABLE [stage].[SAB_ConsLotOptionDetails]
(
[_SysRowId] [varchar] (60) NULL,
[LSN] [varchar] (60) NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[RECID] [bigint] NULL,
[CostPrice] [float] NULL,
[DiscountAmount] [float] NULL,
[DiscountType] [bigint] NULL,
[FinancialInstance] [bigint] NULL,
[ItemId] [varchar] (20) NULL,
[LineAmount] [float] NULL,
[LineNumber] [bigint] NULL,
[Location] [bigint] NULL,
[LocationGroup] [bigint] NULL,
[MeasuredOptionChild] [varchar] (51) NULL,
[Measurement] [float] NULL,
[Name] [varchar] (1000) NULL,
[OPTION_] [bigint] NULL,
[OptionAddSalesPriceToBase] [varchar] (51) NULL,
[OptionIncludedOption] [varchar] (51) NULL,
[OptionMaster] [bigint] NULL,
[RequiredOption] [varchar] (51) NULL,
[SalesPrice] [varchar] (51) NULL,
[SalesPriceOverriden] [varchar] (51) NULL,
[SalesQty] [varchar] (51) NULL,
[Type] [varchar] (51) NULL,
[ZeroPriceIndicator] [bigint] NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[MeasurementUnadjusted] [float] NULL,
[OptionMandatory] [varchar] (51) NULL,
[BaseSalesPriceComponent] [varchar] (51) NULL
) ON [PRIMARY]
GO
