CREATE TABLE [stage].[SAB_ConsVendInvoiceLine]
(
[instance] [bigint] NULL,
[LastProcessedChange_DateTime] [varchar] (50) NULL,
[DataLakeModified_DateTime] [varchar] (50) NULL,
[Start_LSN] [varchar] (50) NULL,
[End_LSN] [varchar] (50) NULL,
[DML_Action] [varchar] (100) NULL,
[Seq_Val] [varchar] (50) NULL,
[Update_Mask] [varchar] (400) NULL,
[RECID] [bigint] NULL,
[Amount] [float] NULL,
[CertificateHold] [varchar] (51) NULL,
[ChangeReason] [bigint] NULL,
[ClaimRequestJour] [bigint] NULL,
[CostCategory] [bigint] NULL,
[CSInsuranceReason] [bigint] NULL,
[CSRequest] [bigint] NULL,
[DefaultDimension] [varchar] (51) NULL,
[FinancialInstance] [bigint] NULL,
[LedgerDimension] [varchar] (51) NULL,
[LineNumber] [bigint] NULL,
[LineType] [varchar] (51) NULL,
[TaxDirectionControl] [varchar] (51) NULL,
[TaxGroup] [varchar] (10) NULL,
[TaxItemGroup] [varchar] (10) NULL,
[TransTxt] [varchar] (120) NULL,
[VendInvoiceTable] [bigint] NULL,
[WorkOrderSummary] [bigint] NULL,
[WrapInsuranceDeduction] [float] NULL,
[WrapInsuranceType] [bigint] NULL,
[ServiceEndDate] [varchar] (40) NULL,
[ServiceStartDate] [varchar] (40) NULL,
[DataAreaId] [varchar] (4) NULL,
[PARTITION] [bigint] NULL,
[RECVERSION] [int] NULL,
[DataArea] [varchar] (4) NULL,
[TradeType] [bigint] NULL
) ON [PRIMARY]
GO
