CREATE SCHEMA [admin]
AUTHORIZATION [dbo]
GO
GRANT DELETE ON SCHEMA:: [admin] TO [biETL]
GO
GRANT EXECUTE ON SCHEMA:: [admin] TO [biETL]
GO
GRANT INSERT ON SCHEMA:: [admin] TO [biETL]
GO
GRANT SELECT ON SCHEMA:: [admin] TO [biETL]
GO
GRANT UPDATE ON SCHEMA:: [admin] TO [biETL]
GO
