GRANT DELETE ON SCHEMA:: [dbo] TO [biETL]
GO
GRANT EXECUTE ON SCHEMA:: [dbo] TO [biETL]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [biETL]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [biETL]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [biETL]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [OLTHOF\Accounting]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [reportsreader]
GO
