CREATE SCHEMA [etl]
AUTHORIZATION [dbo]
GO
GRANT DELETE ON SCHEMA:: [etl] TO [biETL]
GO
GRANT EXECUTE ON SCHEMA:: [etl] TO [biETL]
GO
GRANT INSERT ON SCHEMA:: [etl] TO [biETL]
GO
GRANT SELECT ON SCHEMA:: [etl] TO [biETL]
GO
GRANT UPDATE ON SCHEMA:: [etl] TO [biETL]
GO
GRANT SELECT ON SCHEMA:: [etl] TO [reportsreader]
GO
